### ISSUE TITLE
System.AccessViolationException from Python Runtime

### ISSUE THREAD

**Issue by tomhunter-gh** [QuantConnect/Lean#1031]
Hi @AlexCatarino, thanks for all the hard work with the Python integration.

Unfortunately, I'm getting a System.AccessViolationException when running a Python algorithm.  I have created the following minimal test case:

```python
from clr import AddReference
AddReference("System")
AddReference("QuantConnect.Algorithm")
AddReference("QuantConnect.Common")

from System import *
from QuantConnect import *
from QuantConnect.Algorithm import *


class BasicTemplateAlgorithm_AccessViolationExceptionTest(QCAlgorithm):

    def Initialize(self):
        
        self.SetStartDate(2013,10,07)
        self.SetEndDate(2013,10,11)
        self.SetCash(100000)
        
        self.AddEquity("SPY", Resolution.Second)

        self.orderTicket = None

    def OnData(self, data):
        
        if not self.Portfolio.Invested:            
            self.orderTicket = self.Order("SPY", 1)

        openTime = self.orderTicket.SubmitRequest.Time
        print openTime
```

This prints the `openTime` datetime a few hundred times and then crashes with:

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.Py_CompileString(String code, String file, IntPtr tok)
   at Python.Runtime.PythonEngine.ModuleFromString(String name, String code)
   at Python.Runtime.Converter.TzInfo(Int32 hours, Int32 minutes)
   at Python.Runtime.Converter.ToPython(Object value, Type type)
   at Python.Runtime.PropertyObject.tp_descr_get(IntPtr ds, IntPtr ob, IntPtr tp)
   at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
   at Python.Runtime.PyObject.Invoke(PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , Slice )
   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper.OnData(Slice slice) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\AlgorithmFactory\Python\Wrappers\AlgorithmPythonWrapper.cs:line 642
   at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, IDataFeed feed, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ILeanManagement leanManagement, CancellationToken token) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Engine\AlgorithmManager.cs:line 584
   at QuantConnect.Lean.Engine.Engine.<>c__DisplayClass8_1.<Run>b__2() in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Engine\Engine.cs:line 251
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Any idea where/why this might be going wrong?

I'm on Windows 10, Python 2.7.13 64 bit.

Thanks

**Comment by AlexCatarino** [comment]
Thank you for the report. I will look into it ASAP.

**Comment by tomhunter-gh** [comment]
Unfortunately I'm also getting the below exception half way through a back test.  I'm not easily able to figure out what is causing it..

```
Unhandled Exception: System.AccessViolationException: Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
   at Python.Runtime.Runtime.PyType_GenericAlloc(IntPtr type, Int32 n)
   at Python.Runtime.ExtensionType..ctor()
   at Python.Runtime.MethodBinding..ctor(MethodObject m, IntPtr target, IntPtr targetType)
   at Python.Runtime.MethodObject.tp_descr_get(IntPtr ds, IntPtr ob, IntPtr tp)
   at Python.Runtime.Runtime.PyObject_GetAttrString(IntPtr pointer, String name)
   at Python.Runtime.PyObject.GetAttr(String name)
   at Python.Runtime.PyObject.InvokeMethod(String name, PyTuple args, PyDict kw)
   at Python.Runtime.PyObject.TryInvokeMember(InvokeMemberBinder binder, Object[] args, Object& result)
   at CallSite.Target(Closure , CallSite , Object , Slice )
   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper.OnData(Slice slice) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\AlgorithmFactory\Python\Wrappers\AlgorithmPythonWrapper.cs:line 642
   at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, IDataFeed feed, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ILeanManagement leanManagement, CancellationToken token) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Engine\AlgorithmManager.cs:line 584
   at QuantConnect.Lean.Engine.Engine.<>c__DisplayClass8_1.<Run>b__2() in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Engine\Engine.cs:line 251
   at System.Threading.Tasks.Task.Execute()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
   at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
```

Curiously I'm not actually specifying an OnData(Slice) method in my algorithm (I'm using consolidators).

**Comment by denfromufa** [comment]
@AlexCatarino @tomhunter-gh this could be one of 3 issues:

1. not keeping correctly the reference count for some PyObject
2. not keeping the GIL when calling into Python runtime
3. not keeping lock on some shared object between threads

If you can separate this issue to pythonnet code without calls into QuantConnect, feel free to report it in pythonnet issue tracker.

**Comment by tomhunter-gh** [comment]
Hi @AlexCatarino, I was just wondering if you have had any luck with this one?  Unfortunately I am not able to complete a back test as it crashes with the above error.  I tried creating a **ConsolidatorPythonWrapper** to wrap calls to Python methods with `using (Py.GIL()) { ... }` but that didn't seem to help..

```
System.AccessViolationException was unhandled
  HResult=-2147467261
  Message=Attempted to read or write protected memory. This is often an indication that other memory is corrupt.
  Source=Python.Runtime
  StackTrace:
       at Python.Runtime.Runtime.PyObject_Call(IntPtr pointer, IntPtr args, IntPtr kw)
       at Python.Runtime.PyObject.Invoke(PyObject[] args)
       at Python.Runtime.PythonDerivedType.InvokeMethodVoid(IPythonDerivedType obj, String methodName, String origMethodName, Object[] args)
       at QuantConnect.Data.Consolidators.DataConsolidator`1.Update(IBaseData data) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Common\Data\Consolidators\DataConsolidator.cs:line 39
       at QuantConnect.Python.ConsolidatorPythonWrapper.Update(IBaseData data) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Common\Python\ConsolidatorPythonWrapper.cs:line 109
       at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, IDataFeed feed, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ILeanManagement leanManagement, CancellationToken token) in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Engine\AlgorithmManager.cs:line 480
       at QuantConnect.Lean.Engine.Engine.<>c__DisplayClass8_1.<Run>b__2() in D:\Users\Tom\Dropbox\Algo Trading\QuantConnect\tomhunter-gh\Lean\Engine\Engine.cs:line 251
       at System.Threading.Tasks.Task.Execute()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
       at System.Threading.Tasks.Task.ExecuteEntry(Boolean bPreventDoubleExecution)
       at System.Threading.ThreadPoolWorkQueue.Dispatch()
  InnerException: 
```

**Comment by tomhunter-gh** [comment]
Hi @denfromufa, I was just wondering if you could give me any more details on the steps required to investigate each of the three possible options you've outlined?  I'm not really sure where to start..

The current call is wrapped in `using (Py.GIL()) { ... }`:

![image](https://user-images.githubusercontent.com/1420946/29518655-2a19379e-8672-11e7-9767-267339c9c194.png)

But it still blows up:

![image](https://user-images.githubusercontent.com/1420946/29518593-e2075328-8671-11e7-9bcc-ce5c6a250b3e.png)

Is there any automated/systematic way to determine if _all_ calls to Python are wrapped in Py.GIL()?  I.e. to determine any that are not?

Thanks

**Comment by tomhunter-gh** [comment]
@AlexCatarino @denfromufa 

I just downloaded the latest PythonNet master, built it and referenced that DLL from Lean (rather than the QuantConnect version of PythonNet), and re-ran the test and it didn't blow up this time.  Perhaps the issue has been fixed in PythonNet since the QuantConnect fork was last updated.

**Comment by se-l** [comment]
@tomhunter-gh perhaps issue #1079  and this are very related. I get the same crash when referencing  orderTicket.Time (returns UtcTime) and pulling self.UtcTime. As a workaround I only use self.Time (NY tz) and store that when creating a ,eg, LimitOrder. 
Will also try what you suggest above

**Comment by denfromufa** [comment]
@tomhunter-gh @jaredbroad @se-l looks like that TZ feature is not implemented in pythonnet:

https://github.com/pythonnet/pythonnet/compare/master...QuantConnect:master

Pull requests to pythonnet are welcome! Perhaps we can find out what is wrong during the review process.

**Comment by tomhunter-gh** [comment]
Thanks @denfromufa, understood - it looks like the issue may have been introduced in the changes made in the QuantConnect fork of PythonNet

**Comment by tomhunter-gh** [comment]
Hi @AlexCatarino, I just modified the TzInfo method as below and I was able to run a back test over several years without hitting the AccessViolationException.  My guess is that I'm just delaying the problem rather than fixing it properly.. essentially I'm caching the result of the work done in the method rather than re-compiling/interpreting the Python code every time it's called:

```csharp
static Dictionary<string, IntPtr> _TzInfoCache = new Dictionary<string, IntPtr>();

static IntPtr TzInfo(int hours = 0, int minutes = 0)
{
	var key = string.Format("{0:00}{1:00}", hours, minutes);

	if (_TzInfoCache.ContainsKey(key))
	{
		return _TzInfoCache[key];
	}
	else
	{
		string code = string.Format(
				"from datetime import timedelta, tzinfo\n" +
				"class GMT{0:00}{1:00}(tzinfo):\n" +
				"    def utcoffset(self, dt):\n" +
				"        return timedelta(hours={0:00}, minutes={1:00})\n" +
				"    def tzname(self, dt):\n" +
				"        return \"GMT {0:00}:{1:00}\"\n" +
				"    def dst (self, dt):\n" +
				"        return timedelta(0)\n" +
				"tz=GMT{0:00}{1:00}()",

				hours, minutes);

		IntPtr gs = PythonEngine.AcquireLock();
		try
		{
			var mod = PythonEngine.ModuleFromString("custom_tzinfo", code);
			if (mod == null)
			{
				return Runtime.PyNone;
			}
			else
			{
				var handle = mod.GetAttr("tz").Handle;
				_TzInfoCache.Add(key, handle);
				return handle;
			}
		}
		catch (Exception)
		{
			return Runtime.PyNone;
		}
		finally
		{
			PythonEngine.ReleaseLock(gs);
		}
	}
}
```

Let me know if you have any thoughts..

**Comment by tomhunter-gh** [comment]
Thanks @AlexCatarino, this seems to be working!

**Comment by jaredbroad** [comment]
Thank you @tomhunter-gh for help debugging. Closing as have pending solution.
