### ISSUE TITLE
Build err

### ISSUE THREAD

**Issue by xenu256** [QuantConnect/Lean#15]
Trying to build on fresh Win8 Visual Stduio 2013 Commuity, exception at QuantConnect.Extensions/Extensions.cs

System.ArgumentException was unhandled
  HResult=-2147024809
  Message=Unable to locate any exports matching the requested typeName: QuantConnect.Messaging.Messaging
Parameter name: typeName
  Source=QuantConnect.Common
  ParamName=typeName
  StackTrace:
       at QuantConnect.Extensions.GetExportedValueByTypeName[T](CompositionContainer container, String typeName) in c:\Users\Xenu2\Desktop\Lean-master\Common\Extensions.cs:line 330
       at QuantConnect.Lean.Engine.Engine.Main(String[] args) in c:\Users\Xenu2\Desktop\Lean-master\Engine\Engine.cs:line 188
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException:

**Comment by mchandschuh** [comment]
This is not a build error, but a runtime error.  It looks like you need to clean (delete all files) in your extensions directory (in  engine project). 

This error is typically caused by mismatched dlls when we go to runtime load some components, in this case the IMessaging implementation. 

Also do a full clean of your visual studio solution (right click on solution in solution Explorer and click clean) and then do a full rebuild.

**Comment by xenu256** [comment]
Oh, forgoy Windows adds various junk to folders. All works.
