### ISSUE TITLE
Lean and case sensetive file system

### ISSUE THREAD

**Issue by ksanderer** [QuantConnect/Lean#2113]
I have default Windows 10 instalation with NTFS SSD, with case sensetive paths.
Project crashes during basic initalizaion that makes local debugging totally impossible.

#### Expected Behavior
Project basic examples should work out of the box :)

#### Actual Behavior
During  DirectoryCatalog initalization:
https://github.com/QuantConnect/Lean/blob/c88a88ebc525e5dc5d3bc5750cc926c23b48c41c/Common/Util/Composer.cs#L205

`DirectoryCatalog.GetFullPath(path)`  returns upper cased path and tryies to find `*.dll` and `*.exe` in non-existing path:

![image](https://user-images.githubusercontent.com/1606635/41371444-02c165e8-6f53-11e8-9283-62337326bda7.png)

```
Unhandled Exception: System.TypeInitializationException: The type initializer for 'QuantConnect.Util.Composer' threw an exception. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\USERS\KSAND\SOURCE\REPOS\LEA
N\LAUNCHER\BIN\DEBUG'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.GetFiles(String path, String searchPattern)
   at System.ComponentModel.Composition.Hosting.DirectoryCatalog.GetFiles()
   at System.ComponentModel.Composition.Hosting.DirectoryCatalog.Initialize(String path, String searchPattern)
   at QuantConnect.Util.Composer.Reset() in C:\Users\ksand\source\repos\Lean\Common\Util\Composer.cs:line 205
   at QuantConnect.Util.Composer..ctor() in C:\Users\ksand\source\repos\Lean\Common\Util\Composer.cs:line 49
   at QuantConnect.Util.Composer..cctor() in C:\Users\ksand\source\repos\Lean\Common\Util\Composer.cs:line 41
   --- End of inner exception stack trace ---
   at QuantConnect.Lean.Launcher.Program.Main(String[] args) in C:\Users\ksand\source\repos\Lean\Launcher\Program.cs:line 58
```

#### Reproducing the Problem
I have default Windows 10 instalation with NTFS SSD, have no idea why I have case sensetive paths.

#### System Information
Windows 10, NTFS file system with enabled case sensetive paths.

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Very strange; we run fine on Linux which is also case sensitive and it works fine. I think the bug is the System.Composer on your computer is returning a capitalized path:
`'C:\USERS\KSAND\SOURCE\REPOS\LEAN\LAUNCHER\BIN\DEBUG'.`
This should be a normal cased path. 

Perhaps you're running a strange C# runtime? .Net Core?

**Comment by ksanderer** [comment]
> Perhaps you're running a strange C# runtime? .Net Core?

You are right. Have installed mono and issue is gone.

What is proper .Net version to work with?

**Comment by jaredbroad** [comment]
Cool! .NET 4.5.2 and above or Mono latest,
