### ISSUE TITLE
Update Jupyter/readme to instruct users to use setup.py to install pythonnet

### ISSUE THREAD

**Issue by kevinyuan** [QuantConnect/Lean#2475]
**Environment**

    Python version: Pytnon 3.6.5
    Operating System: osx 10.12.3

**Describe what you were trying to get done.**

    Install Jupyter by following the instrucion from: https://github.com/QuantConnect/Lean/tree/master/Jupyter/readme.md

**What commands:**

   pip install jupyter
   pip install quantconnect
   git clone https://github.com/QuantConnect/pythonnet
   cd pythonnet
   python setup.py install

**Screen output:**
...
XBuild Engine Version 14.0
Mono, Version 5.12.0.0
Copyright (C) 2005-2013 Various Mono authors
                Configuration: ReleaseMono Platform: x64
delegatemanager.cs(204,13): warning CS0162: Unreachable code detected
runtime.cs(332,17): warning CS0162: Unreachable code detected
pythonexception.cs(67,13): warning CS0162: Unreachable code detected
pyobject.cs(51,13): warning CS0162: Unreachable code detected
pyscope.cs(534,13): warning CS0162: Unreachable code detected
Configuration: ReleaseMono Platform: x64
Configuration: ReleaseMono Platform: x64
dynamic.cs(121,28): warning CS0618: 'PythonEngine.RunString(string, IntPtr?, IntPtr?)' is obsolete: 'RunString is deprecated and will be removed. Use Exec/Eval/RunSimpleString instead.'
Configuration: ReleaseMono Platform: x64
Package mono-2 was not found in the pkg-config search path.
Perhaps you should add the directory containing `mono-2.pc'
to the PKG_CONFIG_PATH environment variable
No package 'mono-2' found
Traceback (most recent call last):
  File "setup.py", line 527, in <module>
    zip_safe=False,
  File "/Users/kevinyuan/works/lean0905a/lib/python3.6/site-packages/setuptools/__init__.py", line 140, in setup
    return distutils.core.setup(**attrs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 459, in run
    return install.install.run(self)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/install.py", line 545, in run
    self.run_command('build')
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 339, in run
    self.build_extensions()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 448, in build_extensions
    self._build_extensions_serial()
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/distutils/command/build_ext.py", line 473, in _build_extensions_serial
    self.build_extension(ext)
  File "setup.py", line 269, in build_extension
    self._build_monoclr()
  File "setup.py", line 284, in _build_monoclr
    mono_libs = _check_output("pkg-config --libs mono-2", shell=True)
  File "setup.py", line 98, in _check_output
    output = subprocess.check_output(*args, **kwargs)
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 336, in check_output
    **kwargs).stdout
  File "/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command 'pkg-config --libs mono-2' returned non-zero exit status 1.

**Comment by AlexCatarino** [comment]
Hi @kevinyuan , could you please try to install pythonnet using [setup.py](https://github.com/QuantConnect/Lean/blob/master/setup.py)?

If it installs pythonnet successfully, we will fix [Jupyter/readme](https://github.com/QuantConnect/Lean/blob/master/Jupyter/readme.md), since step 3 should point to this script.

**Comment by kevinyuan** [comment]
Hi Alex,

Yes I can successfully install pythonnet using setup.py.

Thanks.

**Comment by AlexCatarino** [comment]
Thank you, @kevinyuan.
I changed the topic name to reflect the actual issue ([Jupyter/readme](https://github.com/QuantConnect/Lean/blob/master/Jupyter/readme.md) is outdated).

**Comment by Martin-Molinero** [comment]
This was closed by https://github.com/QuantConnect/Lean/pull/2421
