### ISSUE TITLE
Capture Lean Data "file not found" silently and report on the end of algorithm

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#2785]
#### Expected Behavior
`File not found` messages are not logged during algorithm execution. The list of files that were not found should be written to sys log only at the end of the algorithm execution.

#### Actual Behavior
Every time the algorithm try to open an unexisting file of Lean data to read, it logs the failure.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

**Comment by Doggie52** [comment]
Perhaps would be worth extending this to the "corrupt zip file/entry" errors too?

Example of error I'm talking about:
```
20190122 09:47:18.795 ERROR:: ZipDataCacheProvider.Fetch(): Corrupt zip file/entry: {path}QC\Data/cfd\oanda\minute\cornusd\20090101_quote.zip# Error: Ionic.Zip.ZipException: Cannot read that as a ZipFile ---> Ionic.Zip.BadReadException:   Bad signature (0x656D227B) at position  0x00000000
   at Ionic.Zip.ZipEntry.ReadHeader(ZipEntry ze, Encoding defaultEncoding)
   at Ionic.Zip.ZipEntry.ReadEntry(ZipContainer zc, Boolean first)
   at Ionic.Zip.ZipFile.ReadIntoInstance_Orig(ZipFile zf)
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   --- End of inner exception stack trace ---
   at Ionic.Zip.ZipFile.ReadIntoInstance(ZipFile zf)
   at Ionic.Zip.ZipFile.Read(Stream zipStream, TextWriter statusMessageWriter, Encoding encoding, EventHandler`1 readProgress)
   at QuantConnect.Lean.Engine.DataFeeds.CachedZipFile..ctor(Stream dataStream, String key)
   at QuantConnect.Lean.Engine.DataFeeds.ZipDataCacheProvider.Fetch(String key)
```

Due to #2796, these are the most common non-fatal warnings I'm getting.

**Comment by Martin-Molinero** [comment]
This is already available since we added the [data monitor](https://github.com/QuantConnect/Lean/blob/master/Common/Data/DataMonitor.cs), on the end of the algorithm a summary of missing and found files will be logged and the complete details will be available on disk. See https://github.com/QuantConnect/Lean/pull/6725
