### ISSUE TITLE
Need support with installation setup.py for Windows

### ISSUE THREAD

**Issue by skwelker** [QuantConnect/Lean#2793]
I am having issues when running the setup.py script.  I am getting red error in command prompt saying "failed building wheel for pythonnet".  I have thoroughly followed the setup instructions multiple times, and still no luck.  Can someone please help me?

`
Python support in Lean with pythonnet
    =====================================

    Prerequisites:
        - Python 3.6 x64 with pip
        - LEAN: https://github.com/QuantConnect/Lean#installation-instructions
        - Visual C++ for Python: https://www.microsoft.com/en-us/download/details.aspx?id=44266
        - git

    It will update conda, pip, wheel, setuptools, pandas packages.

    Install/updates required packages
    ---------------------------------

[ pip ] Successfully installed/updated: pandas, wheel, setuptools, pip

    Install/updates pythonnet
    -------------------------

  Failed building wheel for pythonnet
Command "C:\Users\skwelker\AppData\Local\Programs\Python\Python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\skwelker\AppData\Local\Temp\pip-record-o655kw2r\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\skwelker\AppData\Local\Temp\pip-req-build-4alttsz8\
Collecting git+https://github.com/QuantConnect/pythonnet
  Cloning https://github.com/QuantConnect/pythonnet to c:\\users\\skwelker\\appdata\\local\\temp\\pip-req-build-4alttsz8
Building wheels for collected packages: pythonnet
  Running setup.py bdist_wheel for pythonnet: started
  Running setup.py bdist_wheel for pythonnet: finished with status 'error'
  Complete output from command C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\python.exe -u -c "import setuptools, tokenize;__file__=\'C:\\\\Users\\\\skwelker\\\\AppData\\\\Local\\\\Temp\\\\pip-req-build-4alttsz8\\\\setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" bdist_wheel -d C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-wheel-hkb9r7jb --python-tag cp36:
  running bdist_wheel
  running build
  running build_ext
  Checking for updates from https://www.nuget.org/api/v2/.
  Currently running NuGet.exe 4.1.0.
  Updating NuGet.exe to 4.9.2.
  Update successful.
  MSBuild auto-detection: using msbuild version '15.9.21.664' from 'C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\MSBuild\\15.0\\bin'.
  Restoring NuGet package NUnit.3.7.1.
  Restoring NuGet package NUnit.ConsoleRunner.3.7.0.
  Restoring NuGet package UnmanagedExports.1.2.7.
  Adding package 'NUnit.3.7.1' to folder 'C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\packages'
  Adding package 'UnmanagedExports.1.2.7' to folder 'C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\packages'
  Adding package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\packages'
  Added package 'UnmanagedExports.1.2.7' to folder 'C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\packages'
  Added package 'NUnit.ConsoleRunner.3.7.0' to folder 'C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\packages'
  Added package 'NUnit.3.7.1' to folder 'C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\packages'

  NuGet Config files used:
      C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\NuGet.Config
      C:\\Users\\skwelker\\AppData\\Roaming\\NuGet\\NuGet.Config
      C:\\Program Files (x86)\\NuGet\\Config\\Microsoft.VisualStudio.Offline.config

  Feeds used:
      C:\\Users\\skwelker\\.nuget\\packages\\
      https://dotnet.myget.org/F/dotnet-core/api/v3/index.json
      https://api.nuget.org/v3/index.json
      C:\\Program Files (x86)\\Microsoft SDKs\\NuGetPackages\\

  Installed:
      3 package(s) to packages.config projects
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\setup.py", line 527, in <module>
      zip_safe=False,
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\setuptools\\__init__.py", line 143, in setup
      return distutils.core.setup(**attrs)
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\core.py", line 148, in setup
      dist.run_commands()
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\dist.py", line 955, in run_commands
      self.run_command(cmd)
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\setup.py", line 475, in run
      return bdist_wheel.bdist_wheel.run(self)
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\site-packages\\wheel\\bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\command\\build.py", line 135, in run
      self.run_command(cmd_name)
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\dist.py", line 974, in run_command
      cmd_obj.run()
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\command\\build_ext.py", line 339, in run
      self.build_extensions()
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\command\\build_ext.py", line 448, in build_extensions
      self._build_extensions_serial()
    File "C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\lib\\distutils\\command\\build_ext.py", line 473, in _build_extensions_serial
      self.build_extension(ext)
    File "C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\setup.py", line 257, in build_extension
      manifest = self._get_manifest(dest_dir)
    File "C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\setup.py", line 274, in _get_manifest
      mt = self._find_msbuild_tool("mt.exe", use_windows_sdk=True)
    File "C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-req-build-4alttsz8\\setup.py", line 392, in _find_msbuild_tool
      raise RuntimeError("{0} could not be found".format(tool))
  RuntimeError: mt.exe could not be found

  ----------------------------------------
  Running setup.py clean for pythonnet
Failed to build pythonnet
Installing collected packages: pythonnet
  Found existing installation: pythonnet 2.3.0
    Uninstalling pythonnet-2.3.0:
      Successfully uninstalled pythonnet-2.3.0
  Running setup.py install for pythonnet: started
    Running setup.py install for pythonnet: finished with status 'error'
    Complete output from command C:\\Users\\skwelker\\AppData\\Local\\Programs\\Python\\Python36\\python.exe -u -c "import setuptools, tokenize;__file__=\'C:\\\\Users\\\\skwelker\\\\AppData\\\\Local\\\\Temp\\\\pip-req-build-4alttsz8\\\\setup.py\';f=getattr(tokenize, \'open\', open)(__file__);code=f.read().replace(\'\\r\\n\', \'\\n\');f.close();exec(compile(code, __file__, \'exec\'))" install --record C:\\Users\\skwelker\\AppData\\Local\\Temp\\pip-record-o655kw2r\\install-record.txt --single-version-externally-managed --compile:
    usage: -c [global_opts] cmd1 [cmd1_opts] [cmd2 [cmd2_opts] ...]
       or: -c --help [cmd1 cmd2 ...]
       or: -c --help-commands
       or: -c cmd --help

    error: option --single-version-externally-managed not recognized

    ----------------------------------------
  Rolling back uninstall of pythonnet
`

**Comment by skwelker** [comment]
Not totally sure what the issue was, but I uninstalled/reinstalled everything and it's working.  I may have left out the step of installing C++ for python 2.7 originally.  Working fine now!

**Comment by michaelsrew** [comment]
Hi.
does a backtest of a python algo work in your environment (windows + python)?
Installation pythonnet works for me but after that rebuilding Lean fails with build errors.

**Comment by skwelker** [comment]
Yes it does.

**Comment by michaelsrew** [comment]
hmm ok thank you
