### ISSUE TITLE
RandomDataGenerator Fails to Create Futures Data

### ISSUE THREAD

**Issue by gsalaz98** [QuantConnect/Lean#2840]
#### Expected Behavior

I am able to generate futures data

#### Actual Behavior

I am not able to generate futures data. The exception message reads: 

```
Unhandled Exception: System.ArgumentException: The provided maximum percent deviation must be a postive number
   at QuantConnect.ToolBox.RandomDataGenerator.RandomValueGenerator.NextPrice(SecurityType securityType, String market, Decimal referencePrice, Decimal maximumPercentDeviati
on) in C:\Users\gsal\Projects\lean\ToolBox\RandomDataGenerator\RandomValueGenerator.cs:line 70
```
On line 63 in `TickGenerator.cs`, there is a call to `NextTick` with the following parameters: 
```C#
var nextQuote = _random.NextTick(symbol, next, TickType.Quote, nextTrade.Value, 0m);
```
Following the method call, we get brought to the file `RandomValueGenerator.cs` and method `NextTick`. On line 208, `NextTick` is called:
```C#
var next = NextPrice(symbol.SecurityType, symbol.ID.Market, previousValue, maximumPercentDeviation);
```
In the method `NextPrice`, there exists a check to ensure that `maximumPercentDeviation` cannot be a value below zero.
```C#
if (maximumPercentDeviation <= 0)
{
    throw new ArgumentException("The provided maximum percent deviation must be a postive number");
}
```

However, given that the exception will be thrown for all values equal to or less than zero, our original invocation with `maximumPercentDeviation = 0m` will always trigger this exception.

#### Potential Solution

Change the `maximumPercentDevation` check to not include 0:

```C#
if (maximumPercentDeviation < 0)
{
    throw new ArgumentException("The provided maximum percent deviation must be a postive number");
}
```
#### Reproducing the Problem

Run the following command:

```
.\QuantConnect.ToolBox.exe --app=rdg --from-date="20131006" --to-date="20131013" --security-type=Future --market=usa --symbol-count=1 --data-density=VerySparse --resolution=Second
```

#### System Information

Windows 10

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by mchandschuh** [comment]
I don't think this is the correct solution here. If we're calling the random data generator with a maximum deviation of zero then why call the random data generator at all? A maximum deviation of zero implies not a random value but the reference value specified. Perhaps the call site should be updated to not pass zero.

**Comment by gsalaz98** [comment]
Agreed. I've come to the same conclusion upon further review. However, it is convenient to call the random tick generator with no deviation, as it creates a copy of the `nextTrade` object and avoids a `NullReferenceException` from being thrown by `LeanDataWriter`. For example, changing the block in `TickGenerator.cs` starting on line 57 to the following:

```C#
var nextTrade = _random.NextTick(symbol, next, TickType.Trade, previousValues[TickType.Trade], deviation);
var nextQuote = nextTrade;
previousValues[TickType.Trade] = nextTrade.Value;
previousValues[TickType.Quote] = nextQuote.Value;
yield return nextTrade;
yield return nextQuote;
```
results in the following error:

```
Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at QuantConnect.ToolBox.LeanDataWriter.WriteMinuteOrSecondOrTick(IEnumerable`1 source) in C:\Users\gsal\Projects\lean\ToolBox\LeanDataWriter.cs:line 102
   at QuantConnect.ToolBox.RandomDataGenerator.RandomDataGeneratorProgram.GenerateRandomData(RandomDataGeneratorSettings settings, ConsoleLeveledOutput output) in C:\Users\gsal\Projects\lean\ToolBox\RandomDataGenerator\RandomDataGeneratorProgram.cs:line 61
   at QuantConnect.ToolBox.RandomDataGenerator.RandomDataGeneratorProgram.RandomDataGenerator(String startDateString, String endDateString, String symbolCountString, String market, String securityTypeString, String resolutionString, String dataDensityString, String inclu
deCoarseString) in C:\Users\gsal\Projects\lean\ToolBox\RandomDataGenerator\RandomDataGeneratorProgram.cs:line 37
   at QuantConnect.ToolBox.Program.Main(String[] args) in C:\Users\gsal\Projects\lean\ToolBox\Program.cs:line 163
```

I figure it's most likely caused by setting `nextQuote` equal to a reference of the `nextTrade` object. Even by cloning the object and casting it as a Tick results in the same error: 
```C#
var nextQuote = (Tick) nextTrade.Clone();
```
Any suggestions on how to fix it would be appreciated. I'll update the PR once I find a suitable solution that involves not calling the random data generator and doesn't throw an exception

**Comment by mchandschuh** [comment]
Ahh, great point! Basically using it as a factory. I suppose my only remaining question is asking if it's desirable to create a new tick with no deviation. Isn't the point to make randomized data? Or is this usage special and I'm missing something?

**Comment by gsalaz98** [comment]
I think that this usage is special. The deviation being set to zero is so that the call to `NextTick` for `nextQuote` with the tick type `TickType.Quote` has the same `Value` that `nextTrade` has. 

From there, we generate the bid/ask prices with a deviation of `Math.Max(0.1m, maximumPercentDeviation / 10m)` and assign the bid/ask prices and volume to the members `BidPrice, BidSize, AskPrice, AskSize`. 
The reason the assignment/cloning of the trade object wasn't working was because those members were null. 

So, random data is generated even with the `maximumPercentDeviation` being equal to zero; `NextTick` ensures that `TickType.Quote` tickTypes have a minimum deviation of 0.001% (with a minimum of 10 iterations).

**Comment by mchandschuh** [comment]
I was able to sit down and take a closer look at this. The zero deviation was provided in an attempt to make the quote tick's bid/ask bracket the trade tick's price, but thinking more about it, the only reason this is of concern is because we're forcing the generator to create a tick and a quote at the same time step. I think forcing a quote tick for every trade tick doesn't seem necessary and in fact, quotes should be given more frequently than trade ticks (configurable). I've posted a PR to address this and have confirmed that futures data is being generated. Also - this issue applied to any security type where both trades and quotes were being generated.
