### ISSUE TITLE
Error on portfolio statistics calculation for large losses

### ISSUE THREAD

**Issue by jameschch** [QuantConnect/Lean#4357]
#### Expected Behavior
After running Forex algorithm with large Net loss should calculate statistics.

#### Actual Behavior
This can return Infinity:

```  
return Math.Pow((performance.Average() + 1), tradingDaysPerYear) - 1;
```

And then throws:

```
20200430 21:22:44.397 ERROR:: BaseResultsHandler.GenerateStatisticsResults(): BaseResultsHandler.GenerateStatisticsResults(): Error generating statistics packet System.OverflowException: Value was either too large or too small for a Decimal.
   at System.Decimal..ctor(Double value)
   at System.Decimal.op_Explicit(Double value)
   at QuantConnect.Statistics.PortfolioStatistics.GetAnnualPerformance(List`1 performance, Int32 
```

You will then not get any statistics.

Has happened with several different Forex algorithms and think it is a combination of many trading days and large net loss. May happen for other security types.

If you need to train machine learning models they will complete with large losses a multitude of times but you still need to know how badly it failed.

#### Potential Solution
PortfolioStatistics line 285:

`            return (Statistics.AnnualPerformance(performance, (double)tradingDaysPerYear)).SafeDecimalCast();
`

#### System Information
win 10

#### Checklist
- [x ] I have completely filled out this template
- [x ] I have confirmed that this issue exists on the current `master` branch
- [x ] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x ] I have provided detailed steps to reproduce the issue

**Comment by jameschch** [comment]
After trying the proposed solution of adding SafeDecimalCast() it appears this will result in a zero annual return and a very high Sharpe Ratio. I am instead preferring to revert change 0d791ec3:

Statistics.cs line 457:

`            return performance.Average() * tradingDaysPerYear;
`

This will result in a zero annual return and a more meaningful negative Sharpe ratio. Perhaps a better solution would also produce a negative decimal for annual return?

**Comment by jameschch** [comment]
Looked into this further and concluded it is probably not an issue. I am using some old data without the full bid ask OHLC that you use as standard now. This means the parse was incorrect and prices were corrupted, resulting in infeasibly large losses. I do not think with valid data it would be right to expect such large losses so this should quite rightly throw an exception.
