### ISSUE TITLE
Tweak ConsoleSetupHandler loader to be more user friendly.

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#456]
ConsoleSetupHandler searches for the algorithm name using a simple function.
https://github.com/QuantConnect/Lean/blob/31df999452f32490fcd1901edb2abf5990662e5c/Engine/Setup/ConsoleSetupHandler.cs#L92

If it can't find the algorithm name it dies with:
```
ERROR:: Loader.TryCreateILAlgorithm():  System.InvalidOperationException: Sequence contains no matching element
  at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
  at QuantConnect.Lean.Engine.Setup.ConsoleSetupHandler.<>c__DisplayClass21_0.<CreateAlgorithmInstance>b__0(List`1 names) in C:\Users\bryan\Downloads\Lean-master\Lean-master\Engine\Setup\ConsoleSetupHandler.cs:line 92
  at QuantConnect.AlgorithmFactory.Loader.TryCreateILAlgorithm(String assemblyPath, IAlgorithm& algorithmInstance, String& errorMessage) in C:\Users\bryan\Downloads\Lean-master\Lean-master\AlgorithmFactory\Loader.cs:line 286
```

This should be made more user friendly so new users know they have specified the wrong algorithm name in the config file.

**Comment by jaredbroad** [comment]
Closed by 648e4b1
