### ISSUE TITLE
Remove YahooDataDownloader from LEAN ToolBox

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#4686]
#### Expected Behavior

- YahooDataDownloader does not fail to download Split & dividends.
#### Actual Behavior

- YahooDataDownloader failing download split & dividend.
```

System.FormatException : Input string was not in a correct format.
   at System.Number.StringToNumber(String str, NumberStyles options, NumberBuffer& number, NumberFormatInfo info, Boolean parseDecimal)
   at System.Number.ParseDecimal(String value, NumberStyles options, NumberFormatInfo numfmt)
   at QuantConnect.Parse.Decimal(String value) in D:\QuantConnect\MyLean\Lean\Common\Parse.cs:line 126
   at QuantConnect.ToolBox.YahooDownloader.YahooDataDownloader.DownloadSplitAndDividendData(Symbol symbol, DateTime startUtc, DateTime endUtc) in D:\QuantConnect\MyLean\Lean\ToolBox\YahooDownloader\YahooDataDownloader.cs:line 113
   at QuantConnect.Tests.Common.Util.FactorFileGeneratorTests.FactorFiles_CanBeGenerated_Accurately() in D:\QuantConnect\MyLean\Lean\Tests\Common\Util\FactorFileGeneratorTests.cs:line 73

```
#### Potential Solution

- Review format & update YahooDataDownloader  
#### Reproducing the Problem

- See `FactorFileGeneratorTests`
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by jamesculshaw** [comment]
Hi,

I would like to do this if its still available
