### ISSUE TITLE
ObjectStore fails to retrieve certain objects

### ISSUE THREAD

**Issue by C-SELLERS** [QuantConnect/Lean#4887]
#### Expected Behavior

Object Store can store and retrieve all types of objects in JSON format

#### Actual Behavior

ObjectStore fails to retrieve Slice object from a JSON file storage

#### Potential Solution

Break is occurring in Newtonsoft.Json library, we could test possibly updating the library to see if this de-serialization issue is a problem with it or if the issue lies within Lean and has to do with the Slice obj itself.

#### Reproducing the Problem

Run the following in an Algorithm twice, on the second time when it attempts to read the Slice it will fail
```
        public override void OnData(Slice slice)
        {
            var timeString = $"{slice.Time}";

            if (!ObjectStore.ContainsKey(timeString))
            {
                Debug($"Storing Data Slice at {timeString}");
                ObjectStore.SaveJson(timeString, slice);
            }
            else
            {
                Debug($"Slice already saved at key {timeString}");
                var test = ObjectStore.ReadJson<Slice>(timeString);
                Debug($"Stored TimeSlice var = {test}");
                ObjectStore.Delete(timeString);
            }
        }
```

Exception Call Stack:
```
Newtonsoft.Json.JsonSerializationException: Cannot create and populate list type QuantConnect.Data.Slice. Path '', line 1, position 1.
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateNewList(JsonReader reader, JsonArrayContract contract, Boolean& createdFromNonDefaultCreator)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateList(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, Object existingValue, String id)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
   at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at QuantConnect.Storage.ObjectStore.ReadJson[T](String key, Encoding encoding, JsonSerializerSettings settings) in C:\Users\Colton\Desktop\QuantConnect\LEAN\Common\Storage\ObjectStore.cs:line 153
   at QuantConnect.Algorithm.CSharp.ObjectStoreExampleAlgorithm.OnData(Slice slice) in C:\Users\Colton\Desktop\QuantConnect\LEAN\Algorithm.CSharp\ObjectStoreExampleAlgorithm.cs:line 52
   at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, ISynchronizer synchronizer, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ILeanManager leanManager, IAlphaHandler alphas, CancellationToken token) in C:\Users\Colton\Desktop\QuantConnect\LEAN\Engine\AlgorithmManager.cs:line 617
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Note that this is probably more due to the nature of the `QuantConnect.Data.Slice` object not being able to survive a roundtrip JSON serialization than to the object store. A nice unit test would be having a Slice pass-through this roundtrip JSON serialization case independently of the object store 👍

**Comment by Martin-Molinero** [comment]
Closing this issue for now
