### ISSUE TITLE
Coinbase Pro Live Trading doesn't work on EUR account

### ISSUE THREAD

**Issue by PaoloOranges** [QuantConnect/Lean#5349]
#### Expected Behavior
Having a valid account on Coinbase Pro in EURO. Create an algorithm that trade any Crypto in Eur (eg ETHEUR, BTCEUR). Setting up your algorithm should work and you should be able to subscribe receiving Ticks.

#### Actual Behavior

- Engine subscribe, via GDAX Brokerage, to receive ticks on selected Coin-Currency Pair (eg ETHEUR, BTCEUR)
- Engine subscribe, via GDAX Brokerage, to receive ticks on BTCUSD (by default)
- Engine subscribe, via GDAX Brokerage, to receive ticks for EURUSD (that does not return anything).
- Engine report an error for and stop with an exception.

#### Potential Solution
TBD

#### Reproducing the Problem

- Setup an EUR account on Coinbase Pro.
- Create an algorithm and subscribe to any Crypto-Eur pair: ie ETHEUR
- run your algorithm in "LIVE" mode.
- See output log for errors

#### System Information
- Windows 10 Pro
- .NET Framework

#### Output Log

```
20210228 10:12:02.238 TRACE:: JOB HANDLERS:
20210228 10:12:02.238 TRACE::          DataFeed:     QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed
20210228 10:12:02.238 TRACE::          Setup:        QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler
20210228 10:12:02.240 TRACE::          RealTime:     QuantConnect.Lean.Engine.RealTime.LiveTradingRealTimeHandler
20210228 10:12:02.240 TRACE::          Results:      QuantConnect.Lean.Engine.Results.LiveTradingResultHandler
20210228 10:12:02.241 TRACE::          Transactions: QuantConnect.Lean.Engine.TransactionHandlers.BrokerageTransactionHandler
20210228 10:12:02.241 TRACE::          Alpha:        QuantConnect.Lean.Engine.Alphas.DefaultAlphaHandler
20210228 10:12:02.241 TRACE::          ObjectStore:  QuantConnect.Lean.Engine.Storage.LocalObjectStore
20210228 10:12:02.241 TRACE::          History Provider:     QuantConnect.Lean.Engine.HistoricalData.BrokerageHistoryProvider
20210228 10:12:02.242 TRACE::          Brokerage:      QuantConnect.Brokerages.GDAX.GDAXDataQueueHandler
20210228 10:12:02.251 TRACE:: LiveTradingRealTimeHandler.RefreshMarketHoursToday(Crypto): Market hours set: Symbol: ETHEUR Open All Day (UTC)
20210228 10:12:02.252 TRACE:: LiveTradingRealTimeHandler.RefreshMarketHoursToday(Forex): Market hours set: Symbol: EURUSD 8G Sunday: Market: 17:00:00-1.00:00:00 (America/New_York)
20210228 10:12:02.252 TRACE:: LiveTradingRealTimeHandler.RefreshMarketHoursToday(Crypto): Market hours set: Symbol: BTCEUR XJ Open All Day (UTC)
20210228 10:12:02.262 TRACE:: LiveTradingResultHandler.SendStatusUpdate(): status: 'Running'.
20210228 10:12:02.276 TRACE:: AlgorithmManager.Run(): Begin DataStream - Start: 28/02/2021 00:00:00 Stop: 31/12/2050 00:00:00
20210228 10:12:02.281 TRACE:: ProcessVolatilityHistoryRequirements(): Updating volatility models with historical data...
20210228 10:12:02.282 TRACE:: ProcessVolatilityHistoryRequirements(): finished.
20210228 10:12:02.292 TRACE:: AlgorithmManager.Stream(): WarmupHistoryRequest: ETHEUR: Start: 28/02/2021 09:42:00 End: 28/02/2021 10:12:00 Resolution: Minute
20210228 10:12:02.293 TRACE:: AlgorithmManager.Stream(): WarmupHistoryRequest: EURUSD 8G: Start: 24/01/2021 00:00:00 End: 28/02/2021 10:12:00 Resolution: Daily
20210228 10:12:02.293 TRACE:: AlgorithmManager.Stream(): WarmupHistoryRequest: BTCEUR XJ: Start: 29/01/2021 00:00:00 End: 28/02/2021 10:12:00 Resolution: Daily
20210228 10:12:02.294 TRACE:: GDAXBrokerage.GetHistory(): Submitting request: ETHEUR: Minute 28/02/2021 09:42:00 UTC -> 28/02/2021 10:12:00 UTC
20210228 10:12:02.355 TRACE:: Debug: Launching analysis for PaoloFastMinuteCryptoAlgorithm with LEAN Engine v2.5.0.0
20210228 10:12:02.434 TRACE:: GDAXBrokerage.GetHistory(): Submitting request: BTCEUR: Daily 29/01/2021 00:00:00 UTC -> 28/02/2021 10:12:00 UTC
20210228 10:12:02.699 TRACE:: Debug: GDAX account base currency: EUR
Changing account currency from USD to EUR...
Algorithm warming up...
20210228 10:12:03.288 TRACE:: LiveTradingResultHandler.SendStatusUpdate(): status: 'History'.  Catching up to realtime 34%...
20210228 10:12:04.288 TRACE:: LiveTradingResultHandler.SendStatusUpdate(): status: 'History'.  Catching up to realtime 60%...
20210228 10:12:05.288 TRACE:: LiveTradingResultHandler.SendStatusUpdate(): status: 'History'.  Catching up to realtime 86%...
20210228 10:12:12.610 TRACE:: EventBasedDataQueueHandlerSubscriptionManager.Subscribe(): ETHEUR
20210228 10:12:12.617 TRACE:: GDAXBrokerage.Subscribe: Sent subscribe.
20210228 10:12:12.618 TRACE:: DataManager.AddSubscription(): Added ETHEUR,ETHEUR,Minute,TradeBar,Trade,Adjusted. Start: 28/02/2021 10:12:06. End: 31/12/2050 00:00:00
20210228 10:12:13.262 TRACE:: DataManager.AddSubscription(): Added ETHEUR,ETHEUR,Minute,QuoteBar,Quote,Adjusted. Start: 28/02/2021 10:12:06. End: 31/12/2050 00:00:00
20210228 10:12:13.677 TRACE:: EventBasedDataQueueHandlerSubscriptionManager.Subscribe(): BTCUSD
20210228 10:12:13.678 TRACE:: GDAXBrokerage.Subscribe: Sent subscribe.
20210228 10:12:13.679 TRACE:: DataManager.AddSubscription(): Added BTCUSD,BTCUSD,Minute,TradeBar,Trade,Adjusted,Internal. Start: 28/02/2021 10:11:00. End: 31/12/2050 00:00:00
20210228 10:12:13.679 TRACE:: UniverseSelection.AddPendingInternalDataFeeds(): Adding internal benchmark data feed BTCUSD,BTCUSD,Minute,TradeBar,Trade,Adjusted,Internal
20210228 10:12:14.175 TRACE:: EventBasedDataQueueHandlerSubscriptionManager.Subscribe(): EURUSD
20210228 10:12:14.701 TRACE:: GDAXBrokerage.Subscribe: Sent subscribe.
20210228 10:12:14.701 TRACE:: DataManager.AddSubscription(): Added EURUSD,EURUSD,Minute,QuoteBar,Quote,Adjusted,Internal. Start: 28/02/2021 10:12:06. End: 31/12/2050 00:00:00
20210228 10:12:14.701 TRACE:: GDAXBrokerage.PollLatestTick: started polling for ticks: EURUSD
20210228 10:12:15.383 TRACE:: EventBasedDataQueueHandlerSubscriptionManager.Subscribe(): BTCEUR
20210228 10:12:16.332 TRACE:: GDAXBrokerage.Subscribe: Sent subscribe.
20210228 10:12:16.332 TRACE:: DataManager.AddSubscription(): Added BTCEUR,BTCEUR,Minute,TradeBar,Trade,Adjusted,Internal. Start: 28/02/2021 10:12:06. End: 31/12/2050 00:00:00
20210228 10:12:16.334 ERROR:: Brokerage.OnMessage(): Error - Code: 0 - GetConversionRate: Prices endpoint is no longer supported
20210228 10:12:16.337 TRACE:: GDAXBrokerage.PollLatestTick: started polling for ticks: EURUSD
20210228 10:12:16.337 TRACE:: AlgorithmManager.Stream(): Finished warmup
20210228 10:12:16.791 TRACE:: AlgorithmManager.Run(): Algorithm encountered a runtime error at 02/28/2021 10:12:06. Error: System.Exception: GetConversionRate: Prices endpoint is no longer supported
20210228 10:12:16.791 TRACE:: Engine.Run(): Exiting Algorithm Manager
20210228 10:12:16.793 ERROR:: Engine.HandleAlgorithmError(): Breaking out of parent try catch: System.Exception: GetConversionRate: Prices endpoint is no longer supported
20210228 10:12:16.794 TRACE:: LiveTradingDataFeed.Exit(): Start. Setting cancellation token...
20210228 10:12:16.794 TRACE:: BaseDataExchange(CustomDataExchange) Stopping...
20210228 10:12:16.794 TRACE:: LiveTradingDataFeed.Exit(): Exit Finished.
20210228 10:12:16.795 TRACE:: BaseDataExchange(CustomDataExchange).ConsumeQueue(): Cancellation requested.  Exiting...
20210228 10:12:17.035 TRACE:: Engine.Run(): Sending runtime error to user...
20210228 10:12:17.039 TRACE:: StopSafely(): waiting for 'Transaction Thread' thread to stop...
20210228 10:12:17.048 TRACE:: BrokerageTransactionHandler.Run(): Ending Thread...
20210228 10:12:17.049 TRACE:: StopSafely(): waiting for 'RealTime Thread' thread to stop...
20210228 10:12:17.091 TRACE:: Log: Runtime Error: GetConversionRate: Prices endpoint is no longer supported
20210228 10:12:17.092 ERROR:: Runtime Error: GetConversionRate: Prices endpoint is no longer supported
 System.Exception: GetConversionRate: Prices endpoint is no longer supported
20210228 10:12:18.056 TRACE:: LiveTradingRealTimeHandler.Run(): Exiting thread... Exit triggered: True
20210228 10:12:19.080 TRACE:: EventBasedDataQueueHandlerSubscriptionManager.Unsubscribe(): EURUSD
20210228 10:12:19.121 ERROR:: DataQueueHandlerSubscriptionManager.Unsubscribe():  System.ArgumentException: Invalid market: oanda
   at QuantConnect.Brokerages.SymbolPropertiesDatabaseSymbolMapper.GetBrokerageSymbol(Symbol symbol) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Brokerages\SymbolPropertiesDatabaseSymbolMapper.cs:line 82
   at QuantConnect.Brokerages.GDAX.GDAXBrokerage.<Unsubscribe>b__54_0(Symbol s) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Brokerages\GDAX\GDAXBrokerage.Messaging.cs:line 502
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at QuantConnect.Brokerages.GDAX.GDAXBrokerage.Unsubscribe(IEnumerable`1 symbols) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Brokerages\GDAX\GDAXBrokerage.Messaging.cs:line 501
   at QuantConnect.Brokerages.GDAX.GDAXDataQueueHandler.<.ctor>b__0_1(IEnumerable`1 s, TickType t) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Brokerages\GDAX\GDAXDataQueueHandler.cs:line 45
   at QuantConnect.Data.EventBasedDataQueueHandlerSubscriptionManager.Unsubscribe(IEnumerable`1 symbols, TickType tickType) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Common\Data\EventBasedDataQueueHandlerSubscriptionManager.cs:line 79
   at QuantConnect.Data.DataQueueHandlerSubscriptionManager.Unsubscribe(SubscriptionDataConfig dataConfig) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Common\Data\DataQueueHandlerSubscriptionManager.cs:line 81
20210228 10:12:19.137 ERROR:: DataManager.RemoveAllSubscriptions(): DataManager.RemoveAllSubscriptions():Error removing: EURUSD,EURUSD,Minute,QuoteBar,Quote,Adjusted,Internal System.ArgumentException: Invalid market: oanda
   at QuantConnect.Brokerages.SymbolPropertiesDatabaseSymbolMapper.GetBrokerageSymbol(Symbol symbol) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Brokerages\SymbolPropertiesDatabaseSymbolMapper.cs:line 82
   at QuantConnect.Brokerages.GDAX.GDAXBrokerage.<Unsubscribe>b__54_0(Symbol s) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Brokerages\GDAX\GDAXBrokerage.Messaging.cs:line 502
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at QuantConnect.Brokerages.GDAX.GDAXBrokerage.Unsubscribe(IEnumerable`1 symbols) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Brokerages\GDAX\GDAXBrokerage.Messaging.cs:line 501
   at QuantConnect.Brokerages.GDAX.GDAXDataQueueHandler.<.ctor>b__0_1(IEnumerable`1 s, TickType t) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Brokerages\GDAX\GDAXDataQueueHandler.cs:line 45
   at QuantConnect.Data.EventBasedDataQueueHandlerSubscriptionManager.Unsubscribe(IEnumerable`1 symbols, TickType tickType) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Common\Data\EventBasedDataQueueHandlerSubscriptionManager.cs:line 79
   at QuantConnect.Data.DataQueueHandlerSubscriptionManager.Unsubscribe(SubscriptionDataConfig dataConfig) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Common\Data\DataQueueHandlerSubscriptionManager.cs:line 90
   at QuantConnect.Brokerages.GDAX.GDAXDataQueueHandler.Unsubscribe(SubscriptionDataConfig dataConfig) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Brokerages\GDAX\GDAXDataQueueHandler.cs:line 88
   at QuantConnect.Lean.Engine.DataFeeds.LiveTradingDataFeed.RemoveSubscription(Subscription subscription) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Engine\DataFeeds\LiveTradingDataFeed.cs:line 142
   at QuantConnect.Lean.Engine.DataFeeds.DataManager.RemoveSubscription(SubscriptionDataConfig configuration, Universe universe) in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Engine\DataFeeds\DataManager.cs:line 240
   at QuantConnect.Lean.Engine.DataFeeds.DataManager.RemoveAllSubscriptions() in F:\SourceCode\ExternalProjects\QuantitativeTrading\Lean\Engine\DataFeeds\DataManager.cs:line 157
20210228 10:12:19.467 TRACE:: EventBasedDataQueueHandlerSubscriptionManager.Unsubscribe(): BTCEUR
20210228 10:12:19.476 TRACE:: DataManager.RemoveSubscription(): Removed BTCEUR,BTCEUR,Minute,TradeBar,Trade,Adjusted,Internal
20210228 10:12:19.797 TRACE:: EventBasedDataQueueHandlerSubscriptionManager.Unsubscribe(): BTCUSD
20210228 10:12:19.798 TRACE:: DataManager.RemoveSubscription(): Removed BTCUSD,BTCUSD,Minute,TradeBar,Trade,Adjusted,Internal
20210228 10:12:20.565 TRACE:: DataManager.RemoveSubscription(): Removed ETHEUR,ETHEUR,Minute,TradeBar,Trade,Adjusted
20210228 10:12:20.973 TRACE:: DataManager.RemoveSubscription(): Removed QC-UNIVERSE-USERDEFINED-GDAX-CRYPTO,QC-UNIVERSE-USERDEFINED-GDAX-CRYPTO,Minute,TradeBar,Trade,Adjusted,Internal
20210228 10:12:21.445 TRACE:: EventBasedDataQueueHandlerSubscriptionManager.Unsubscribe(): ETHEUR
20210228 10:12:21.447 TRACE:: DataManager.RemoveSubscription(): Removed ETHEUR,ETHEUR,Minute,QuoteBar,Quote,Adjusted
20210228 10:12:21.460 TRACE:: DefaultAlphaHandler.Exit(): Exiting...
20210228 10:12:21.475 TRACE:: DefaultAlphaHandler.Exit(): Ended
20210228 10:12:21.478 TRACE:: StopSafely(): waiting for 'Result Thread' thread to stop...
20210228 10:12:21.539 TRACE:: Debug: Algorithm finished warming up.
20210228 10:12:21.540 ERROR:: Brokerage Error: GetConversionRate: Prices endpoint is no longer supported
Brokerage Error: GetConversionRate: Prices endpoint is no longer supported
20210228 10:12:21.540 TRACE:: LiveTradingResultHandler.Run(): Ending Thread...
20210228 10:12:21.542 TRACE:: LiveTradingResultHandler.SendFinalResult(): Starting...
20210228 10:12:21.610 TRACE:: LiveTradingResultHandler.SendFinalResult(): Finished storing results. Start sending...
20210228 10:12:21.611 TRACE:: LiveTradingResultHandler.SendFinalResult(): Ended
20210228 10:12:21.613 TRACE:: Engine.Run(): Disconnecting from brokerage...
20210228 10:12:21.634 TRACE:: WebSocketClientWrapper connection task ended: wss://ws-feed.pro.coinbase.com
20210228 10:12:21.634 TRACE:: WebSocketClientWrapper.OnClose(): Connection closed (IsOpen:False, State:Aborted): wss://ws-feed.pro.coinbase.com
20210228 10:12:21.634 TRACE:: GDAXBrokerage.FillMonitorAction(): task ended
20210228 10:12:21.635 TRACE:: Engine.Run(): Disposing of setup handler...
20210228 10:12:21.635 TRACE:: BrokerageSetupHandler.Setup(): Found data queue handler to dispose: QuantConnect.Brokerages.GDAX.GDAXDataQueueHandler
20210228 10:12:21.636 TRACE:: Engine.Main(): Analysis Completed and Results Posted.
20210228 10:12:21.636 TRACE:: StopSafely(): waiting for 'Transaction Thread' thread to stop...
Engine.Main(): Analysis Complete.
20210228 10:12:21.636 TRACE:: Config.GetValue(): close-automatically - Using default value: False
Engine.Main(): Press any key to continue.
20210228 10:12:22.591 TRACE:: PollLatestTick: stopped polling for ticks: EURUSD
20210228 10:12:22.591 TRACE:: PollLatestTick: stopped polling for ticks: EURUSD
```

#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by PaoloOranges** [comment]
I've investigated a bit more, this issue might be related partially with: 
https://github.com/QuantConnect/Lean/issues/4859

and to this function: 
https://github.com/QuantConnect/Lean/blob/60798df64cb7fcdee4bdcce5c12ef1e4e92906d0/Brokerages/GDAX/GDAXBrokerage.Messaging.cs#L386-L406

Specifically, when `PollTick` is called: https://github.com/QuantConnect/Lean/blob/60798df64cb7fcdee4bdcce5c12ef1e4e92906d0/Brokerages/GDAX/GDAXBrokerage.Messaging.cs#L446-L479

always return empty conversion. At this point the system start shutdown process.

Later there's another issue. On subscribe for ticker: 
https://github.com/QuantConnect/Lean/blob/60798df64cb7fcdee4bdcce5c12ef1e4e92906d0/Common/Data/DataQueueHandlerSubscriptionManager.cs#L39-L61

here is what I have:
![image](https://user-images.githubusercontent.com/6449340/109415418-e94ccd00-79b8-11eb-967d-2b45aea6ae7b.png)

When system is shutting down and closing all the subscription, this:
https://github.com/QuantConnect/Lean/blob/60798df64cb7fcdee4bdcce5c12ef1e4e92906d0/Common/Data/DataQueueHandlerSubscriptionManager.cs#L67-L92
is called with `dataConfig`:
![image](https://user-images.githubusercontent.com/6449340/109415574-bd7e1700-79b9-11eb-9549-c1f154af99f1.png)

that trigger an Unsubscribe from Oanda that never happend, causing another exception. 
Specifically, this is called: 
https://github.com/QuantConnect/Lean/blob/60798df64cb7fcdee4bdcce5c12ef1e4e92906d0/Brokerages/GDAX/GDAXBrokerage.Messaging.cs#L497-L515
with 
![image](https://user-images.githubusercontent.com/6449340/109415614-f3230000-79b9-11eb-8339-1b2c42e3a248.png)

and here:
https://github.com/QuantConnect/Lean/blob/60798df64cb7fcdee4bdcce5c12ef1e4e92906d0/Brokerages/GDAX/GDAXBrokerage.Messaging.cs#L501-L503

Since symbol `EURUSD` is not present in `_symbolMapper`, an exception is thrown.

I guess the second part of the error is just on De-init, but the first part, related to https://github.com/QuantConnect/Lean/issues/4859 is blocking the engine to live trade on GDAX/CoinbasePro in Eur

**Comment by Martin-Molinero** [comment]
Hey @PaoloOranges! This is probably because GDAX is reporting account currency being USD, see https://github.com/QuantConnect/Lean/blob/master/Engine/Setup/BrokerageSetupHandler.cs#L213. Have you tried calling SetAccountCurrency during `algorithm.Initialize()`

**Comment by PaoloOranges** [comment]
Hi @Martin-Molinero . Thanks for the info. I didn't have `SetAccountCurrency` in the Initialize function of my algorithm. I've added it but I've noticed that it is called after the line you mentioned: 
https://github.com/QuantConnect/Lean/blob/master/Engine/Setup/BrokerageSetupHandler.cs#L213

Unless there's a `PreInitialize`, like `PostInitialize`, that is called before Initialize and before this: 
https://github.com/QuantConnect/Lean/blob/master/Engine/Setup/BrokerageSetupHandler.cs#L213

`SetAccountCurrency` will not affect that check.

**Comment by PaoloOranges** [comment]
I did try to set AccountCurrency before Initialize, as workaround:
```
public MyAlgorhythm() : base()
{
    SetAccountCurrency(CurrencyName);
}
```
Now here :
https://github.com/QuantConnect/Lean/blob/master/Engine/Setup/BrokerageSetupHandler.cs#L213
check is ok but since by default a `BTCUSD` pair is added (and I think this is by design, am I wrong?) the system fall to the same situation requesting Conversion `EURUSD` and having that Exception thrown on https://github.com/QuantConnect/Lean/blob/60798df64cb7fcdee4bdcce5c12ef1e4e92906d0/Brokerages/GDAX/GDAXBrokerage.Messaging.cs#L456

**Comment by StefanoRaggi** [comment]
@PaoloOranges 
`SetAccountCurrency` should not be called from the algorithm as it's already set automatically to EUR by the brokerage (as you can see from the log above):
```
20210228 10:12:02.699 TRACE:: Debug: GDAX account base currency: EUR
Changing account currency from USD to EUR...
```
but you are correct about the issue with `PollTick` causing the runtime error because the old price provider is no longer enabled.
The EURUSD conversion rate is required in your algorithm because you added the BTCUSD pair (and this caused the USD currency to be added to the cash book).
In fact if you don't subscribe any USD pairs, the error would not occur.

To solve this problem (which only affects local Lean users, because in the cloud we automatically get live Forex data from Oanda), I believe we need to replace/update the price provider with one capable of fetching Forex prices from somewhere.

**Comment by PaoloOranges** [comment]
@StefanoRaggi thanks for the answer. Is it possible that BTCUSD is automatically added? I'm not explicitly subscribe for that in my algorithm. 
There's also a comment in the code similar to what you says https://github.com/QuantConnect/Lean/blob/60798df64cb7fcdee4bdcce5c12ef1e4e92906d0/Brokerages/GDAX/GDAXBrokerage.Messaging.cs#L402-L404

**Comment by StefanoRaggi** [comment]
@PaoloOranges This is strange, I also have an EUR account and subscribing only EUR pairs I don't see the error, could you please post only your `Initialize` method here?

**Comment by PaoloOranges** [comment]
Sure

```
        private const string CryptoName = "ETH";
        private const string CurrencyName = "EUR";
        private const string SymbolName = CryptoName + CurrencyName;

        public override void Initialize()
        {
            SetBrokerageModel(BrokerageName.GDAX, AccountType.Cash);
            SetTimeZone(NodaTime.DateTimeZone.Utc);
            SetAccountCurrency(CurrencyName);

            Resolution resolution = Resolution.Minute;

            SetStartDate(2021, 02, 15); // Set Start Date
            SetEndDate(2021, 02, 20); // Set End Date

            SetCash(CurrencyName, 1000, 1.21m);
            //SetCash("USD", 0);
            //SetCash(CryptoName, 0.08m);

            _symbol = AddCrypto(SymbolName, resolution, Market.GDAX).Symbol;

            const int veryFastValue = 5;
            const int fastValue = 10;
            const int slowValue = 30;
            const int signal = 8;

            _very_fast_ema = EMA(_symbol, veryFastValue, resolution);
            _fast_ema = EMA(_symbol, fastValue, resolution);
            _slow_ema = EMA(_symbol, slowValue, resolution);
            _macd = MACD(_symbol, fastValue, slowValue, signal, MovingAverageType.Exponential, resolution);
            _adx = ADX(_symbol, 2, resolution);
            _roc = ROC(_symbol, veryFastValue, resolution);

            SetWarmUp(30);           

        }
```

**Comment by StefanoRaggi** [comment]
Ok, the `USD` currency is being added to the cashbook because of the default `SPY` benchmark, 
you can change it to be your symbol:
`SetBenchmark(_symbol);`
or set it to be a constant:
`SetBenchmark(t => 0);`

You can also remove this line:
`SetAccountCurrency("EUR");`
the account currency should already be set to `EUR` in the `BrokerageSetupHandler` before `Initialize` is called

**Comment by PaoloOranges** [comment]
Yep I was writing almost the same, that by default a BTCUSD benchmark is added by GDAXBrokerageModel: 
https://github.com/QuantConnect/Lean/blob/60798df64cb7fcdee4bdcce5c12ef1e4e92906d0/Common/Brokerages/GDAXBrokerageModel.cs#L110-L114

I will do as you said. Thanks again

**Comment by Martin-Molinero** [comment]
Closing this issue for now, since https://github.com/QuantConnect/Lean/pull/5158 benchmark is per brokerage model. Related https://github.com/QuantConnect/Lean/issues/4855
