### ISSUE TITLE
KeyNotFoundException in Cash.EnsureCurrencyDataFeed Live Algorithm Deployed to Oanda

### ISSUE THREAD

**Issue by AlexCatarino** [QuantConnect/Lean#5539]
#### Expected Behavior
No unhandled exception.

#### Actual Behavior
```
System.Collections.Generic.KeyNotFoundException: The given key 'Crypto' was not present in the dictionary.
```
at Cash.EnsureCurrencyDataFeed:

```
Engine.Run(): During the algorithm initialization, the following exception has occurred: System.Collections.Generic.KeyNotFoundException: The given key 'Crypto' was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at System.Collections.ObjectModel.ReadOnlyDictionary`2.get_Item(TKey key)
   at QuantConnect.Securities.Cash.EnsureCurrencyDataFeed(SecurityManager securities, SubscriptionManager subscriptions, IReadOnlyDictionary`2 marketMap, SecurityChanges changes, ISecurityService securityService, String accountCurrency, Resolution defaultResolution) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Securities/Cash.cs:line 291
   at QuantConnect.Securities.CashBook.EnsureCurrencyDataFeeds(SecurityManager securities, SubscriptionManager subscriptions, IReadOnlyDictionary`2 marketMap, SecurityChanges changes, ISecurityService securityService, Resolution defaultResolution) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Securities/CashBook.cs:line 119
   at QuantConnect.Lean.Engine.DataFeeds.CurrencySubscriptionDataConfigManager.EnsureCurrencySubscriptionDataConfigs(SecurityChanges securityChanges, IBrokerageModel brokerageModel) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/CurrencySubscriptionDataConfigManager.cs:line 140
   at QuantConnect.Lean.Engine.DataFeeds.UniverseSelection.EnsureCurrencyDataFeeds(SecurityChanges securityChanges) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/UniverseSelection.cs:line 455
   at QuantConnect.Lean.Engine.Setup.BaseSetupHandler.SetupCurrencyConversions(IAlgorithm algorithm, UniverseSelection universeSelection) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BaseSetupHandler.cs:line 56
   at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.Setup(SetupHandlerParameters parameters) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BrokerageSetupHandler.cs:line 320The given key 'Crypto' was not present in the dictionary.
```

#### Potential Solution
N/A

#### Reproducing the Problem
Deploy [BasicTemplateForexAlgorithm](https://github.com/QuantConnect/Lean/blob/master/Algorithm.Python/BasicTemplateForexAlgorithm.py) in live mode to Oanda account denominated in EUR.

#### Checklist
- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)
- [x] I have provided detailed steps to reproduce the issue

**Comment by ebengtso** [comment]
this defect is a blocker, since algorithms cannot be deployed in QC with oanda.

**Comment by Martin-Molinero** [comment]
> 
> 
> this defect is a blocker, since algorithms cannot be deployed in QC with oanda.

Believe the underlying issue here should be solved by https://github.com/QuantConnect/Lean/pull/5552, https://github.com/QuantConnect/Lean/pull/5558 will only change the exception message, since there was missing a dictionary contains key check

**Comment by ebengtso** [comment]
thanks, deployment works
