### ISSUE TITLE
ForexInternalFeedOnDataHigherResolutionRegressionAlgorithm Fails Intermittently

### ISSUE THREAD

**Issue by Martin-Molinero** [QuantConnect/Lean#5858]
#### Expected Behavior

- ForexInternalFeedOnDataHigherResolutionRegressionAlgorithm is consistent
#### Actual Behavior

- ForexInternalFeedOnDataHigherResolutionRegressionAlgorithm fails intermittently 
```
20210812 15:24:48.679 ERROR:: Extensions.SetRuntimeError(): Extensions.SetRuntimeError(): RuntimeError at 10/10/2013 12:00:00 AM UTC. Context: OnEndOfAlgorithm System.Exception: Data point count mismatch for symbol EURGBP: expected: 3, actual: 26
   at QuantConnect.Algorithm.CSharp.ForexInternalFeedOnDataHigherResolutionRegressionAlgorithm.OnEndOfAlgorithm() in /__w/Lean/Lean/Algorithm.CSharp/ForexInternalFeedOnDataHigherResolutionRegressionAlgorithm.cs:line 116
   at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, ISynchronizer synchronizer, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ILeanManager leanManager, IAlphaHandler alphas, CancellationToken token) in /__w/Lean/Lean/Engine/AlgorithmManager.cs:line 625
```
#### Potential Solution

Review underlying issue
#### Reproducing the Problem

N/A
#### System Information

N/A
#### Checklist

- [x] I have completely filled out this template
- [x] I have confirmed that this issue exists on the current `master` branch
- [x] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [x] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
This issue probably falls into one of these cases https://github.com/QuantConnect/Lean/issues/6253 https://github.com/QuantConnect/Lean/issues/6255
