### ISSUE TITLE
QCAlgorithm Python package documentation missing

### ISSUE THREAD

**Issue by PeterCHK** [QuantConnect/Lean#5892]
Expected Behavior
Download data successfully without QCAlgorithm python package missing. 

Actual Behavior
I inputted login credentials and pulled projects. Then I tried to download data with
`lean backtest 07volatilityeffectinstocks --download-data`

It seems QCAlgorithm Python package is missing and caused download error. I tried to look everything and pip install QCAlgorithm to try my luck but in vain. The stack trace was
```
20210901 09:25:58.697 TRACE:: Config.Get(): Configuration key not found. Key: plugin-directory - Using default value:
20210901 09:25:58.720 TRACE:: Composer(): Loading Assemblies from /Lean/Launcher/bin/Debug
20210901 09:25:58.791 TRACE:: Python for .NET Assembly: QuantConnect.DataSource.ExamplePythonScriptMyCustomDataTypeDoNotUse, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
20210901 09:25:58.838 TRACE:: Python for .NET Assembly: Python.Runtime, Version=2.0.6.0, Culture=neutral, PublicKeyToken=5000fea6cba702dd
20210901 09:25:59.801 TRACE:: Config.Get(): Configuration key not found. Key: data-directory - Using default value: ../../../Data/
20210901 09:25:59.803 TRACE:: Config.Get(): Configuration key not found. Key: version-id - Using default value:
20210901 09:25:59.803 TRACE:: Config.Get(): Configuration key not found. Key: cache-location - Using default value: /Lean/Data
20210901 09:25:59.803 TRACE:: Engine.Main(): LEAN ALGORITHMIC TRADING ENGINE v2.5.0.0 Mode: DEBUG (64bit) Host: jupyter03
20210901 09:25:59.836 TRACE:: Engine.Main(): Started 9:25 AM
20210901 09:25:59.839 TRACE:: Config.Get(): Configuration key not found. Key: lean-manager-type - Using default value: LocalLeanManager
20210901 09:25:59.925 TRACE:: JobQueue.NextJob(): Selected /LeanCLI/main.py
20210901 09:26:00.144 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-capacity - Using default value: 120
20210901 09:26:00.145 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-time-interval-minutes - Using default value: 1440
20210901 09:26:00.145 TRACE:: Config.GetValue(): scheduled-event-leaky-bucket-refill-amount - Using default value: 18
20210901 09:26:00.146 TRACE:: Config.Get(): Configuration key not found. Key: data-permission-manager - Using default value: DataPermissionManager
20210901 09:26:00.155 TRACE:: Config.GetValue(): data-purchase-limit - Using default value: 79228162514264337593543950335
20210901 09:26:02.910 TRACE:: ApiDataProvider(): Data Terms of Use has been signed.
 Find full agreement at: https://www.quantconnect.com/terms/data/?organization=bda5240639f194add4f267c4bb848230
==========================================================================
CLI API Access Agreement: On 9/1/2021 You Agreed:
 - Display or distribution of data obtained through CLI API Access is not permitted.
 - Data and Third Party Data obtained via CLI API Access can only be used for individual or internal employee's use.
 - Data is provided in LEAN format can not be manipulated for transmission or use in other applications.
 - QuantConnect is not liable for the quality of data received and is not responsible for trading losses.
==========================================================================
20210901 09:26:05.944 TRACE:: AlgorithmManager.CreateTokenBucket(): Initializing LeakyBucket: Capacity: 120 RefillAmount: 18 TimeInterval: 1440
20210901 09:26:05.954 TRACE:: Config.GetValue(): algorithm-manager-time-loop-maximum - Using default value: 20
20210901 09:26:05.982 TRACE:: TextSubscriptionDataSourceReader.SetCacheSize(): Setting cache size to 71582788 items
20210901 09:26:06.340 TRACE:: Config.GetValue(): algorithm-creation-timeout - Using default value: 90
20210901 09:26:06.342 TRACE:: PythonInitializer.Initialize(): start...
PythonEngine.Initialize(): Runtime.Initialize()...
Runtime.Initialize(): Py_Initialize...
Runtime.Initialize(): PyEval_InitThreads...
Runtime.Initialize(): Initialize types...
Runtime.Initialize(): Initialize types end.
Runtime.Initialize(): AssemblyManager.Initialize()...
Runtime.Initialize(): AssemblyManager.UpdatePath()...
PythonEngine.Initialize(): GetCLRModule()...
PythonEngine.Initialize(): clr GetManifestResourceStream...
20210901 09:26:06.759 TRACE:: PythonInitializer.Initialize(): ended
20210901 09:26:06.768 TRACE:: AlgorithmPythonWrapper(): Python version 3.6.8 |Anaconda, Inc.| (default, Dec 30 2018, 01:25:33)
[GCC 7.3.0]: Importing python module main
20210901 09:26:09.869 ERROR:: Loader.TryCreatePythonAlgorithm():  System.Exception: AlgorithmPythonWrapper(): NameError : name 'QCAlgorithm' is not defined
  at <module>
    class ShortTermReversalAlgorithm(QCAlgorithm):
===
   at Python.Runtime.PythonException.ThrowIfIsNull(IntPtr ob)
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at Python.Runtime.Py.Import(String name)
   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper..ctor(String moduleName) at 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs:line 74 in main.py: line 12
 NameError : name 'QCAlgorithm' is not defined
   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper..ctor(String moduleName) in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs:line 146
   at QuantConnect.AlgorithmFactory.Loader.TryCreatePythonAlgorithm(String assemblyPath, IAlgorithm& algorithmInstance, String& errorMessage) in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/AlgorithmFactory/Loader.cs:line 173
20210901 09:26:09.873 ERROR:: Engine.Run():  QuantConnect.Lean.Engine.Setup.AlgorithmSetupException: During the algorithm initialization, the following exception has occurred: 
Loader.TryCreatePythonAlgorithm(): Unable to import python module /LeanCLI/main.py. AlgorithmPythonWrapper(): NameError : name 'QCAlgorithm' is not defined
  at <module>
    class ShortTermReversalAlgorithm(QCAlgorithm):
===
   at Python.Runtime.PythonException.ThrowIfIsNull(IntPtr ob)
   at Python.Runtime.PythonEngine.ImportModule(String name)
   at Python.Runtime.Py.Import(String name)
   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper..ctor(String moduleName) at 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs:line 74 in main.py: line 12
 NameError : name 'QCAlgorithm' is not defined
   at QuantConnect.Lean.Engine.Setup.BacktestingSetupHandler.CreateAlgorithmInstance(AlgorithmNodePacket algorithmNodePacket, String assemblyPath) in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BacktestingSetupHandler.cs:line 104
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in 
/LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Engine.cs:line 116
```

I found something very close to what I need but I am not 100% sure on how I can utilise that, I saw QCAlgorithm.Python.cs in 
https://github.com/QuantConnect/Lean/tree/master/Algorithm
Do I need to convert this file to Python package by myself? Or is there a clever way to find the QCAlgorithm Python package something? 

Background
I have zero knowledge in C# but I still want to give Lean a try on the Python part. 
I have Lean CLI up and running in my Ubuntu 18.04 local server. 

Checklist
+ I have completely filled out this template
+ I have confirmed that this issue exists on the current master branch
+ I have confirmed that this is not a duplicate issue by searching issues
+ I have provided detailed steps to reproduce the issue

**Comment by jmerle** [comment]
Hi Peter,

Some imports are automatically added to your files when you run them in the cloud. This does not happen locally, so in your local environment, you need to manually import all the classes that you use. You can import everything that is automatically imported when running in the cloud by adding `from AlgorithmImports import *` to the top of all the Python files in your project.
