### ISSUE TITLE
Universe Selection not working properly when use another currency from USD

### ISSUE THREAD

**Issue by aytacasan** [QuantConnect/Lean#6077]
#### Expected Behavior

Work without any exception.

#### Actual Behavior

Give an error. Please look at the second attachment.

#### Potential Solution

I looked at engine code that handles algorithms and didn't understand what is the problem.

#### Reproducing the Problem

Please look at the first attachment. The left side is working and the right side is not.

#### System Information

Windows 10 and Lean is the latest version.

#### Checklist

- [x] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

<!--- Template inspired by https://github.com/stevemao/github-issue-templates --
![Code](https://user-images.githubusercontent.com/640271/143367014-f9c116ac-81b4-406f-83fa-5c3e1b36d310.png)
![Error](https://user-images.githubusercontent.com/640271/143367034-cf42552a-6b58-4d49-b1c8-68a19600a6cf.png)
>

**Comment by aytacasan** [comment]
![Code](https://user-images.githubusercontent.com/640271/143367221-481ccad4-4a2e-4cd2-84bf-ef8e7ed1388c.png)
![Error](https://user-images.githubusercontent.com/640271/143367237-140f1672-d95e-41f8-bc86-572a23cd6557.png)

**Comment by aytacasan** [comment]
Today I try to test above algorithms (user universe vs manual universe selection model) on quantconnect.com. And as I expected, I see same error messages on algorithm lab same as local copy of LEAN. Below error message and stacktrace from quantconnect.com:

**Error Message**: Algorithm.Initialize() Error: No conversion path found between source currency BTC and destination currency USDT Stack Trace: System.ArgumentException: No conversion path found between source currency BTC and destination currency USDT
   at QuantConnect.Securities.CurrencyConversion.SecurityCurrencyConversion.LinearSearch(String sourceCurrency, String destinationCurrency, IList`1 existingSecurities, IEnumerable`1 potentialSymbols, Func`2 makeNewSecurity) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Securities/CurrencyConversion/SecurityCurrencyConversion.cs:line 223
   at QuantConnect.Securities.Cash.EnsureCurrencyDataFeed(SecurityManager securities, SubscriptionManager subscriptions, IReadOnlyDictionary`2 marketMap, SecurityChanges changes, ISecurityService securityService, String accountCurrency, Resolution defaultResolution) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Securities/Cash.cs:line 292
   at QuantConnect.Securities.CashBook.EnsureCurrencyDataFeeds(SecurityManager securities, SubscriptionManager subscriptions, IReadOnlyDictionary`2 marketMap, SecurityChanges changes, ISecurityService securityService, Resolution defaultResolution) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Securities/CashBook.cs:line 119
   at QuantConnect.Lean.Engine.DataFeeds.CurrencySubscriptionDataConfigManager.EnsureCurrencySubscriptionDataConfigs(SecurityChanges securityChanges, IBrokerageModel brokerageModel) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/CurrencySubscriptionDataConfigManager.cs:line 140
   at QuantConnect.Lean.Engine.Setup.BaseSetupHandler.SetupCurrencyConversions(IAlgorithm algorithm, UniverseSelection universeSelection) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BaseSetupHandler.cs:line 57
   at QuantConnect.Lean.Engine.Setup.BacktestingSetupHandler.Setup(SetupHandlerParameters parameters) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BacktestingSetupHandler.cs:line 217
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Engine.cs:line 227

**Stacktrace**: System.ArgumentException: No conversion path found between source currency BTC and destination currency USDT
   at QuantConnect.Securities.CurrencyConversion.SecurityCurrencyConversion.LinearSearch(String sourceCurrency, String destinationCurrency, IList`1 existingSecurities, IEnumerable`1 potentialSymbols, Func`2 makeNewSecurity) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Securities/CurrencyConversion/SecurityCurrencyConversion.cs:line 223
   at QuantConnect.Securities.Cash.EnsureCurrencyDataFeed(SecurityManager securities, SubscriptionManager subscriptions, IReadOnlyDictionary`2 marketMap, SecurityChanges changes, ISecurityService securityService, String accountCurrency, Resolution defaultResolution) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Securities/Cash.cs:line 292
   at QuantConnect.Securities.CashBook.EnsureCurrencyDataFeeds(SecurityManager securities, SubscriptionManager subscriptions, IReadOnlyDictionary`2 marketMap, SecurityChanges changes, ISecurityService securityService, Resolution defaultResolution) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Securities/CashBook.cs:line 119
   at QuantConnect.Lean.Engine.DataFeeds.CurrencySubscriptionDataConfigManager.EnsureCurrencySubscriptionDataConfigs(SecurityChanges securityChanges, IBrokerageModel brokerageModel) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/DataFeeds/CurrencySubscriptionDataConfigManager.cs:line 140
   at QuantConnect.Lean.Engine.Setup.BaseSetupHandler.SetupCurrencyConversions(IAlgorithm algorithm, UniverseSelection universeSelection) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BaseSetupHandler.cs:line 57
   at QuantConnect.Lean.Engine.Setup.BacktestingSetupHandler.Setup(SetupHandlerParameters parameters) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Setup/BacktestingSetupHandler.cs:line 217
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Engine/Engine.cs:line 227

**_I'm wondering if this is a bug or is it my fault?_**

**Comment by Martin-Molinero** [comment]
Hey @aytacasan!
>  No conversion path found between source currency BTC and destination currency USDT 

Have you tried specifying `SetBrokerageModel(BrokerageName.Binance)` else Lean using the default brokerage model will use GDAX as default crypto market, where the `BTCUSDT` pair does not exist

**Comment by aytacasan** [comment]
> 

Yes, I try that and still there is an error. Below code from quantconnect.com -> algorithm lab;

`
namespace QuantConnect.Algorithm.CSharp
{
    public class CalculatingVioletAnguilline : QCAlgorithm
    {

        public override void Initialize()
        {
        	SetAccountCurrency("USDT");	// Set Account Currency
        	SetCash(1000000);			// Set Strategy Cash

            SetStartDate(2018, 08, 17);	// Set Start Date
            SetEndDate(2021, 11, 15);	// Set End Date
            
            var tickers = new string[]
            {
            	"ADAUSDT", "BNBUSDT", "BTCUSDT",
            	"ETHUSDT", "LTCUSDT", "SOLUSDT"
            };
            
            //foreach (var ticker in tickers)
            //{
            //	AddCrypto(ticker, Resolution.Daily, Market.Binance);
            //}
            
            var symbols = new List<Symbol>();
            foreach (var ticker in tickers)
            {
            	symbols.Add(QuantConnect.Symbol.Create(ticker, SecurityType.Crypto, Market.Binance));
            }
            
            UniverseSettings.Resolution = Resolution.Daily;
            SetUniverseSelection(new ManualUniverseSelectionModel(symbols));
            
            SetBenchmark("BTCUSDT");
            SetBrokerageModel(BrokerageName.Binance);
        }

        /// OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        /// Slice object keyed by symbol containing the stock data
        public override void OnData(Slice data)
        {
            // if (!Portfolio.Invested)
            // {
            //    SetHoldings("SPY", 1);
            //    Debug("Purchased Stock");
            //}
        }

    }
}
`

**Comment by Martin-Molinero** [comment]
Hey @aytacasan!
`SetBrokerageModel(BrokerageName.Binance);` is throwing an exception, binance only support cash account types for now, using `SetBrokerageModel(BrokerageName.Binance, AccountType.Cash);` will do the trick.

Underlying issue solved by https://github.com/QuantConnect/Lean/pull/6092 is that algorithm setup would report the second error (`No conversion path found between source currency`) because it was still using GDAX as crypto market (because it failed at `SetBrokerageModel(BrokerageName.Binance);`), after the PR it will report the first error asking you to use `AccountType.Cash`

Thanks for the report!

**Comment by aytacasan** [comment]
Hi @Martin-Molinero,
I see and changed above sample code line from
`SetBrokerageModel(BrokerageName.Binance);`
to
`SetBrokerageModel(BrokerageName.Binance, AccountType.Cash);`
then add below lines under `SetUniverseSelection(new ManualUniverseSelectionModel(symbols));`
`   SetAlpha(new ConstantAlphaModel(InsightType.Price, InsightDirection.Up, TimeSpan.FromDays(365)));
    SetPortfolioConstruction(new EqualWeightingPortfolioConstructionModel());
    SetExecution(new ImmediateExecutionModel());
    SetRiskManagement(new NullRiskManagementModel());`

Receive an error : During the algorithm initialization, the following exception has occurred: Non null IExecutionModel and IPortfolioConstructionModel are currently unsuitable for Cash Modeled brokerages (e.g. GDAX) and may result in unexpected trades. To prevent possible user error we've restricted them to Margin trading. You can select margin account types with SetBrokerage( ... AccountType.Margin). Or please set them to NullExecutionModel, NullPortfolioConstructionModel in Framework.cs:line 79 Non null IExecutionModel and IPortfolioConstructionModel are currently unsuitable for Cash Modeled brokerages (e.g. GDAX) and may result in unexpected trades. To prevent possible user error we've restricted them to Margin trading. You can select margin account types with SetBrokerage( ... AccountType.Margin). Or please set them to NullExecutionModel, NullPortfolioConstructionModel.

**What is that mean? we should not use framework feature with cash accounts? Because without execution and portfolio construction, algorithm is meaningless. Am i missing something?**
