### ISSUE TITLE
[Bug] -RandomDataGenerator - String '{{value}}' was not recognized as a valid DateTime.

### ISSUE THREAD

**Issue by BrainTonic** [QuantConnect/Lean#6477]
#### Expected Behavior
- Run without errors and generate random data locally.

#### Actual Behavior
- Seeing numerous errors
  - Generated file, at times creates duplicate columns and `String '{{invalid_date}}' was not recognized as a valid DateTime.`
     - When using Rider | VS (Mac) and running the following command `--destination-dir ../../../Data --app randomdatagenerator --start 20200101 --end 20220101 --symbol-count 1 --security-type Equity --resolution Daily`
     - [odg.zip](https://github.com/QuantConnect/Lean/files/9095367/odg.zip)
     - [odg.csv](https://github.com/QuantConnect/Lean/files/9095408/odg.csv)

     - ```shell
            20220712 16:57:34.750 ERROR:: CoarseUniverseGeneratorProgram.Run(): CoarseUniverseGeneratorProgram.Run(): FAILED! System.AggregateException: One or more errors occurred. (String '1001200' was not recognized as a valid DateTime.)
        ---> System.FormatException: String '1001200' was not recognized as a valid DateTime.
        at System.DateTime.ParseExact(String s, String format, IFormatProvider provider)
        at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.ParseDailyFile(FileInfo dailyFile) in /Users/.../RiderProjects/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 377
        at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.<>c__DisplayClass9_0.<Run>b__0(SecurityIdentifierContext sidContext) in /Users/.../RiderProjects/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 175
        at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
        --- End of stack trace from previous location ---
        at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
        at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
        at System.Threading.Tasks.TaskReplicator.Replica.Execute()
        --- End of inner exception stack trace ---
        at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
        at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
        --- End of stack trace from previous location ---
        at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
        at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
        at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
        at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
        at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.Run() in /Users/.../RiderProjects/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 146
        20220712 16:57:34.750 TRACE:: RandomDataGeneratorProgram(): Press any key to exit...
        ```


   - When using `lean-cli` and docker using the following command `lean data generate --start=20200101 --symbol-count=1 --security-type=Equity`
   - [hte.zip](https://github.com/QuantConnect/Lean/files/9095409/hte.zip)
   - [hte.csv](https://github.com/QuantConnect/Lean/files/9095410/hte.csv)

     - ```shell
        20220712 17:10:28.975 ERROR:: CoarseUniverseGeneratorProgram.Run(): CoarseUniverseGeneratorProgram.Run(): FAILED! System.AggregateException: One or more errors occurred. (String '1009900' was not recognized as a valid DateTime.) (String '1006200' was not
        recognized as a valid DateTime.)
        ---> System.FormatException: String '1009900' was not recognized as a valid DateTime.
        at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.ParseDailyFile(FileInfo dailyFile) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 333
        at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.<>c__DisplayClass9_0.<Run>b__0(SecurityIdentifierContext sidContext) in 
        /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 164
        at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
        --- End of stack trace from previous location ---
        at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
        at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
        at System.Threading.Tasks.TaskReplicator.Replica.Execute()
        --- End of inner exception stack trace ---
        at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
        at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 
        bodyWithEverything, Func`1 localInit, Action`1 localFinally)
        --- End of stack trace from previous location ---
        at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
        at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 
        bodyWithEverything, Func`1 localInit, Action`1 localFinally)
        at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 
        localInit, Action`1 localFinally)
        at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
        at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.Run() in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 138
        ---> (Inner Exception #1) System.FormatException: String '1006200' was not recognized as a valid DateTime.
        at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.ParseDailyFile(FileInfo dailyFile) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 333
        at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.<>c__DisplayClass9_0.<Run>b__0(SecurityIdentifierContext sidContext) in 
        /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 164
        at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
        --- End of stack trace from previous location ---
        at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& replicationDelegateYieldedBeforeCompletion)
        at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
        at System.Threading.Tasks.TaskReplicator.Replica.Execute()<---
        ```

#### System Information
- Macbook Air 13" M1 1st Gen.

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by AlexCatarino** [comment]
Related to https://github.com/QuantConnect/lean-cli/issues/115

**Comment by BrainTonic** [comment]
Just tried an older Docker image (`#14002`) and it still didn't work.
- Command from cli: `lean data generate --start=20200101 --symbol-count=1 --security-type=Equity --image=14002`

Received this error message:
```shell
  20220712 21:32:32.095 TRACE:: CoarseUniverseGeneratorProgram.ProcessDailyFolder(): Processing: /Lean/Data/equity/usa/daily
  20220712 21:32:32.210 TRACE:: CoarseUniverseGeneratorProgram.PopulateSidContex(): Generating SID context from QuantQuote's map files.
  20220712 21:32:32.683 ERROR:: CoarseUniverseGeneratorProgram.Run(): CoarseUniverseGeneratorProgram.Run(): FAILED! System.AggregateException: One or more errors occurred. 
  (String '1026700' was not recognized as a valid DateTime.)
  ---> System.FormatException: String '1026700' was not recognized as a valid DateTime.
    at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.ParseDailyFile(FileInfo dailyFile) in 
  /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 333
    at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.<>c__DisplayClass9_0.<Run>b__0(SecurityIdentifierContext sidContext) in 
  /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 164
    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& 
  replicationDelegateYieldedBeforeCompletion)
  --- End of stack trace from previous location ---
    at System.Threading.Tasks.Parallel.<>c__DisplayClass44_0`2.<PartitionerForEachWorker>b__1(IEnumerator& partitionState, Int32 timeout, Boolean& 
  replicationDelegateYieldedBeforeCompletion)
    at System.Threading.Tasks.TaskReplicator.Replica`1.ExecuteAction(Boolean& yieldedBeforeCompletion)
    at System.Threading.Tasks.TaskReplicator.Replica.Execute()
    --- End of inner exception stack trace ---
    at System.Threading.Tasks.TaskReplicator.Run[TState](ReplicatableUserAction`1 action, ParallelOptions options, Boolean stopOnFirstFailure)
    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, 
  Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
  --- End of stack trace from previous location ---
    at System.Threading.Tasks.Parallel.ThrowSingleCancellationExceptionOrOtherException(ICollection exceptions, CancellationToken cancelToken, Exception otherException)
    at System.Threading.Tasks.Parallel.PartitionerForEachWorker[TSource,TLocal](Partitioner`1 source, ParallelOptions parallelOptions, Action`1 simpleBody, Action`2 bodyWithState, 
  Action`3 bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEachWorker[TSource,TLocal](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body, Action`2 bodyWithState, Action`3 
  bodyWithStateAndIndex, Func`4 bodyWithStateAndLocal, Func`5 bodyWithEverything, Func`1 localInit, Action`1 localFinally)
    at System.Threading.Tasks.Parallel.ForEach[TSource](IEnumerable`1 source, ParallelOptions parallelOptions, Action`1 body)
    at QuantConnect.ToolBox.CoarseUniverseGenerator.CoarseUniverseGeneratorProgram.Run() in 
  /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/ToolBox/CoarseUniverseGenerator/CoarseUniverseGeneratorProgram.cs:line 138
  20220712 21:32:32.683 TRACE:: RandomDataGeneratorProgram(): Press any key to exit...

```
