### ISSUE TITLE
Current master results in errors when changing environment from backtest

### ISSUE THREAD

**Issue by sblanchard** [QuantConnect/Lean#6517]
When running the default backtest environment all is fine, not sure if i'm missing something I'm returning to LEAN after using it some time ago. 
When changing to for example "live-binance" (or anything other than backtest)  I get the following errors:

```
ERROR:: JobQueue.NextJob(): Error resolving BrokerageData for live job for brokerage InteractiveBrokersBrokerage System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuantConnect.Util.Composer.Single[T](Func`2 predicate) in C:\DEV\Lean-master\Common\Util\Composer.cs:line 176
   at QuantConnect.Queues.JobQueue.NextJob(String& location) in C:\DEV\Lean-master\Queues\JobQueue.cs:line 156
```

```
20220729 10:15:39.361 ERROR:: Engine.Run():  System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuantConnect.Util.Composer.Single[T](Func`2 predicate) in C:\DEV\Lean-master\Common\Util\Composer.cs:line 176
   at QuantConnect.Lean.Engine.Setup.BrokerageSetupHandler.CreateBrokerage(AlgorithmNodePacket algorithmNodePacket, IAlgorithm uninitializedAlgorithm, IBrokerageFactory& factory) in C:\DEV\Lean-master\Engine\Setup\BrokerageSetupHandler.cs:line 128
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, AlgorithmManager manager, String assemblyPath, WorkerThread workerThread) in C:\DEV\Lean-master\Engine\Engine.cs:line 135
```

**Comment by Martin-Molinero** [comment]
Hey @sblanchard!
The brokerages have been extracted from Lean into their own repositories, recommend using the https://www.lean.io/cli/ . Will require a subscription, please take a look at https://github.com/QuantConnect/lean-cli/issues/120 for more detail information
