### ISSUE TITLE
Bug report of KerasNeuralNetworkAlgorithm.py

### ISSUE THREAD

**Issue by mit10000** [QuantConnect/Lean#6542]
#### Expected Behavior
The original official Keras LSTM algorithm can be tested without error. 

#### Actual Behavior
I didn't touch the file ../../../Algorithm.Python/KerasNeuralNetworkAlgorithm.py but
ERROR showed up 

#### Reproducing the Problem
Modify config.json to this
    "algorithm-type-name": "official LSTM",
    "algorithm-language": "Python",
    "algorithm-location": "../../../Algorithm.Python/KerasNeuralNetworkAlgorithm.py",
then run 
dotnet QuantConnect.Lean.Launcher.dll

Errors are like
20220811 18:43:25.715 ERROR:: Extensions.SetRuntimeError(): Extensions.SetRuntimeError(): RuntimeError at 1/7/2019 3:00:00 PM UTC. Context: Scheduled event: 'SPY: EveryDay: SPY: 30 min after MarketOpen' at 1/7/2019 3:00:00 PM System.Collections.Generic.KeyNotFoundException: 'SPY' wasn't found in the Slice object, likely because there was no-data at this moment in time and it wasn't possible to fillforward historical data. Please check the data exists before accessing it with data.ContainsKey("SPY")
   at QuantConnect.Data.Slice.get_Item(Symbol symbol) in /home/desheng/Projects/LEAN/Lean/Common/Data/Slice.cs:line 315
--- End of stack trace from previous location ---
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.PyObject.Invoke(PyObject[] args)
   at QuantConnect.Scheduling.ScheduleManager.<>c__DisplayClass15_0.<On>b__0(String name, DateTime time) in /home/desheng/Projects/LEAN/Lean/Common/Scheduling/ScheduleManager.cs:line 142
   at QuantConnect.Scheduling.ScheduledEvent.OnEventFired(DateTime triggerTime) in /home/desheng/Projects/LEAN/Lean/Common/Scheduling/ScheduledEvent.cs:line 259
   at QuantConnect.Scheduling.ScheduledEvent.Scan(DateTime utcTime) in /home/desheng/Projects/LEAN/Lean/Common/Scheduling/ScheduledEvent.cs:line 189
   at QuantConnect.IsolatorLimitResultProvider.<>c__DisplayClass1_0.<Consume>b__0() in /home/desheng/Projects/LEAN/Lean/Common/IsolatorLimitResultProvider.cs:line 48
   at QuantConnect.IsolatorLimitResultProvider.Consume(IIsolatorLimitResultProvider isolatorLimitProvider, ITimeProvider timeProvider, Action code, TimeMonitor timeMonitor) in /home/desheng/Projects/LEAN/Lean/Common/IsolatorLimitResultProvider.cs:line 75
   at QuantConnect.IsolatorLimitResultProvider.Consume(IIsolatorLimitResultProvider isolatorLimitProvider, ScheduledEvent scheduledEvent, DateTime scanTimeUtc, TimeMonitor timeMonitor) in /home/desheng/Projects/LEAN/Lean/Common/IsolatorLimitResultProvider.cs:line 48
   at QuantConnect.Lean.Engine.RealTime.BacktestingRealTimeHandler.SetTime(DateTime time) in /home/desheng/Projects/LEAN/Lean/Engine/RealTime/BacktestingRealTimeHandler.cs:line 109
20220811 18:43:25.963 ERROR:: AlgorithmManager.Run(): Stopping, encountered a runtime error at 1/7/2019 3:00:00 PM UTC.
20220811 18:43:25.963 TRACE:: Engine.Run(): Exiting Algorithm Manager

#### System Information
Ubuntu 16.04
tensorflow 2.0
keras 2.3

#### Checklist

- [ *] I have completely filled out this template
- [* ] I have confirmed that this issue exists on the current `master` branch
- [ *] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ *] I have provided detailed steps to reproduce the issue

**Comment by jaredbroad** [comment]
Algorithm runs successfully in cloud without issue;
https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_856937686339b87e117bc2186492e1ed.html
