### ISSUE TITLE
Binance Live Algo

### ISSUE THREAD

**Issue by agadrim** [QuantConnect/Lean#6648]
When I try to run a strategy in binance live, I get this error
ERROR:: JobQueue.NextJob(): Error resolving BrokerageData for live job for brokerage QuantConnect.BinanceBrokerage.BinanceBrokerage System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.ThrowHelper.ThrowNoMatchException()
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at QuantConnect.Util.Composer.Single[T](Func`2 predicate) in C:\dev\atela\source\Common\Util\Composer.cs:line 176
   at QuantConnect.Queues.JobQueue.NextJob(String& location) in C:\dev\atela\source\Queues\JobQueue.cs:line 156
What m I missing?

**Comment by Martin-Molinero** [comment]
Hey @agadrim! Please take a look at https://github.com/QuantConnect/Lean.Brokerages.Binance#readme
