### ISSUE TITLE
`Portfolio.UnsettledCashBook` is not updated when using `AccountCurrency` different from USD

### ISSUE THREAD

**Issue by ArthurAsenheimer** [QuantConnect/Lean#6859]
#### Expected Behavior

LEAN updates the `UnsettledCashBook` regardless of the chosen `AccountCurrency`.

#### Actual Behavior

The `UnsettledCashBook` remains unchanged when using an `AccountCurrency` other than USD. 

#### Reproducing the Problem

Run [this backtest](https://www.quantconnect.com/terminal/processCache?request=embedded_backtest_b74e91ec7b79c1673f012ce4da09a3ab.html) and view the log file. 

Excerpt of the log file:
```
2022-09-30 10:00:00 OrderEvent:
Time: 09/30/2022 14:00:00 OrderID: 3 EventID: 2 Symbol: TLT Status: Filled Quantity: -15 FillQuantity: -15 FillPrice: 103.3591 USD OrderFee: 1 USD

2022-09-30 10:00:00 OrderEvent:
Time: 09/30/2022 14:00:00 OrderID: 4 EventID: 2 Symbol: SPY Status: Filled Quantity: -3 FillQuantity: -3 FillPrice: 361.42 USD OrderFee: 1 USD

2022-09-30 10:00:00 CashBook:
Symbol      Quantity    Conversion = Value in AUD
USD: $      -61185.23 @     1.5434 = $-94431.13
AUD: $      100000.00 @       1.00 = $100000.0
-------------------------------------------------
CashBook Total Value:                $5568.87


2022-09-30 10:00:00 Unsettled CashBook:
Symbol      Quantity    Conversion = Value in AUD
AUD: $           0.00 @       1.00 = $0.0
-------------------------------------------------
CashBook Total Value:                $0.0
```

After the two order events, I would have expected an unsettled cash amount of ~2,600 USD. In fact, the USD currency is not even listed as part of the unsettled cash book. 

Note, it might not be related to the USD currency in particular, but rather to the fact that the account currency is not the same as the quote currency of the security.

#### System Information

QC Cloud

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
An exception is being thrown because `UnsettledCashBook` does not hold the USD Cash instance
```
2023-01-16T20:31:45.9291268Z ERROR:: SecurityPortfolioModel.ProcessFill():  System.Collections.Generic.KeyNotFoundException: This cash symbol (USD) was not found in your cash book.
   at QuantConnect.Securities.CashBook.get_Item(String symbol) in Lean/Common/Securities/CashBook.cs:line 334
   at QuantConnect.Securities.DelayedSettlementModel.ApplyFunds(SecurityPortfolioManager portfolio, Security security, DateTime applicationTimeUtc, String currency, Decimal amount) in Lean/Common/Securities/DelayedSettlementModel.cs:line 50
   at QuantConnect.Securities.SecurityPortfolioModel.ProcessFill(SecurityPortfolioManager portfolio, Security security, OrderEvent fill) in Lean/Common/Securities/SecurityPortfolioModel.cs:line 74
```

- The `SecurityService` is the one adding the quote & base currencies (if required) into the cash book. See `SecurityPortfolioManager`, we could wire `CashBook.Updated` to add into `UnsettledCashBook` the new cash instances if `UpdateType.Added`
- Add some unit tests see `SecurityPortfolioManagerTests`, plus a new regression algorithm reproducing the bug
