### ISSUE TITLE
Placing a Take Profit order for a Multileg Option position Iron Fly is not possible

### ISSUE THREAD

**Issue by heikohaensel** [QuantConnect/Lean#7054]
#### Expected Behavior
I open a Iron Fly position using the ComboMarketOrder() method, which results in a position being short a Put and a Call at the ShortStrike and being Long Call and a Put 35 points away from it. This Combo Order gets filled as expected.
When they're filled I want to place a take profit order using CombLimitOrder(this.orderLegs, -1, tpPrice), which means use the same legs as for the opening order but with quantity -1 which would reverse the quantities of the legs.

#### Actual Behavior
Looking at the backtest result, I can see that there are 4 orders submitted, but the orders are the same as for opening the position and not reversed as expected.

#### Potential Solution
Alternatively I tried to reverse the quantities of the leg myself in the coding and use quantity 1 for the combo:
foreach(var leg in this.orderLegs) {
  leg.Quantity = leg.Quantity * -1;
}
var tickets = ComboLimitOrder(this.orderLegs, 1, tpPrice);

But this results in the following error: Backtest Handled Error: Order Error: id: 8, Error executing margin models: Unable to create group for orders: [5,6,7,8]

#### Reproducing the Problem
Here is the code for reproducing this error:
```
#region imports
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using System.Globalization;
    using System.Drawing;
    using QuantConnect;
    using QuantConnect.Algorithm.Framework;
    using QuantConnect.Algorithm.Framework.Selection;
    using QuantConnect.Algorithm.Framework.Alphas;
    using QuantConnect.Algorithm.Framework.Portfolio;
    using QuantConnect.Algorithm.Framework.Execution;
    using QuantConnect.Algorithm.Framework.Risk;
    using QuantConnect.Parameters;
    using QuantConnect.Benchmarks;
    using QuantConnect.Brokerages;
    using QuantConnect.Util;
    using QuantConnect.Interfaces;
    using QuantConnect.Algorithm;
    using QuantConnect.Indicators;
    using QuantConnect.Data;
    using QuantConnect.Data.Consolidators;
    using QuantConnect.Data.Custom;
    using QuantConnect.DataSource;
    using QuantConnect.Data.Fundamental;
    using QuantConnect.Data.Market;
    using QuantConnect.Data.UniverseSelection;
    using QuantConnect.Notifications;
    using QuantConnect.Orders;
    using QuantConnect.Orders.Fees;
    using QuantConnect.Orders.Fills;
    using QuantConnect.Orders.Slippage;
    using QuantConnect.Scheduling;
    using QuantConnect.Securities;
    using QuantConnect.Securities.Equity;
    using QuantConnect.Securities.Future;
    using QuantConnect.Securities.Option;
    using QuantConnect.Securities.Forex;
    using QuantConnect.Securities.Crypto;   
    using QuantConnect.Securities.Interfaces;
    using QuantConnect.Storage;
    using QuantConnect.Data.Custom.AlphaStreams;
    using QCAlgorithmFramework = QuantConnect.Algorithm.QCAlgorithm;
    using QCAlgorithmFrameworkBridge = QuantConnect.Algorithm.QCAlgorithm;
#endregion
namespace QuantConnect.Algorithm.CSharp
{
    public class IronFly : QCAlgorithm
    {
        private Symbol symbol;
        private Option option;
        private List<Leg> orderLegs;
        private TradeBarConsolidator consolidator;

        private AverageTrueRange atr;

        private decimal ifShortStrike;
        private decimal ifPutLongStrike;
        private decimal ifCallLongStrike;
        private decimal wingSize = 35;
        private decimal entryFillPrice;
        private bool doSubmitEntryOrder;
        private bool doSubmitTPOrder;
        private bool tpOrderSubmitted;
        private bool waitForEntryOrderFill;
        private readonly List<OrderTicket> openEntryOrders = new();

        public override void Initialize()
        {
            SetStartDate(2023, 1, 3);  //Set Start Date
            SetCash(100000);             //Set Strategy Cash
            SetEndDate(2023, 1, 3);

            this.symbol = AddIndex("SPX", Resolution.Minute).Symbol;
            this.option = AddIndexOption(this.symbol, "SPXW");
            this.option.SetFilter(optionFilterUniverse => optionFilterUniverse.IncludeWeeklys().Strikes(-10,10).Expiration(0,0));
        
            var atrWindow  = new RollingWindow<IndicatorDataPoint>(5);

            // ATR Indicator
            this.atr = new AverageTrueRange("AvgTrueRange", 9);
            this.atr.Updated += (sender, updated) => atrWindow.Add(updated);

            // Create a 5 min. Consolidator
            this.consolidator = new TradeBarConsolidator(TimeSpan.FromMinutes(5));
            this.consolidator.DataConsolidated += FiveMinuteBarHandler;
            this.consolidator.DataConsolidated += (_, bar) => atr.Update(bar);
            SubscriptionManager.AddConsolidator(this.symbol, this.consolidator);
        }

        /// OnData event is the primary entry point for your algorithm. Each new data point will be pumped in here.
        /// Slice object keyed by symbol containing the stock data
        public override void OnData(Slice data)
        {
            if (doSubmitEntryOrder == true) {
                doSubmitEntryOrder = false;
                var chain = data.OptionChains.GetValue(this.option.Symbol);
                if (chain == null)
                {
                    Debug("ERROR: No Option Chain not found!");
                } else {
                    this.SubmitEntryOrder(chain);
                }
                return;
            } else if (waitForEntryOrderFill == true) {
                if (CheckComboOrderForFills(this.openEntryOrders))
                {
                    this.waitForEntryOrderFill = false;
                    this.entryFillPrice = GetComboOrderFillPrice(this.openEntryOrders);
                    Debug("Entry Order filled at " + this.entryFillPrice);
                    var tpPrice = this.entryFillPrice * -1 - 1;
                    Debug(data.Time + ": Submitting Take Profit Order now");
                    var tickets = ComboLimitOrder(this.orderLegs, -1, tpPrice);
                }
            } 
        }

        private bool CheckComboOrderForFills(List<OrderTicket> orderTickets) {
            if (orderTickets.All(ticket => ticket.Status == OrderStatus.Filled))
                return true;
            else
                return false;
        }

        private decimal GetComboOrderFillPrice(List<OrderTicket> orderTickets) {
            decimal comboFillPrice = 0;
            foreach (var ticket in orderTickets) {
                if (ticket.Status != OrderStatus.Filled)
                    return 0;
                else 
                    comboFillPrice += ticket.AverageFillPrice * ticket.Quantity;
            }
            return comboFillPrice;
        }
        private void SubmitEntryOrder(OptionChain chain) {
            Debug("Short Strike: " + this.ifShortStrike + " Long Put Strike: " + this.ifPutLongStrike + " Long Call Strike: " + this.ifCallLongStrike);
            //callContracts = [contract for contract in chain if contract.Right == OptionRight.Call]
            this.orderLegs = new List<Leg>();
            foreach (var entry in chain.Contracts) {
                var contract = entry.Value;
                if (contract.Right == OptionRight.Put && contract.Strike == this.ifShortStrike) {
                    var leg = Leg.Create(contract.Symbol, -1);
                    this.orderLegs.Add(leg);
                } else if (contract.Right == OptionRight.Call && contract.Strike == this.ifShortStrike) {
                    var leg = Leg.Create(contract.Symbol, -1);
                    this.orderLegs.Add(leg);
                } else if (contract.Right == OptionRight.Put && contract.Strike == this.ifPutLongStrike) {
                    var leg = Leg.Create(contract.Symbol, 1);
                    this.orderLegs.Add(leg);
                } else if (contract.Right == OptionRight.Call && contract.Strike == this.ifCallLongStrike) {
                    var leg = Leg.Create(contract.Symbol, 1);
                    this.orderLegs.Add(leg);
                }
            }
            if (this.orderLegs.Count < 4) {
                Debug("ERROR: 4 Legs are required!");
                return;
            }
            var tickets = ComboMarketOrder(this.orderLegs, 1);
            this.openEntryOrders.AddRange(tickets);
            this.waitForEntryOrderFill = true;
            Debug("INFO: Entry Order submitted.");
        }

        /// <summary>
        /// Called at every 5 Minute Bar
        /// </summary>
        private void FiveMinuteBarHandler(object sender, TradeBar bar)
        {
            if (!this.atr.IsReady) {
                Debug(bar.EndTime + ": ATR not ready");
                return;
            }

            if (!this.Portfolio.Invested && this.Transactions.OrdersCount == 0) {
                this.ifShortStrike = this.CalculateStrike(bar.Close);
                this.ifPutLongStrike = this.ifShortStrike - this.wingSize;
                this.ifCallLongStrike = this.ifShortStrike + this.wingSize;
                Debug(bar.EndTime + ": Short Strike " + this.ifShortStrike);

                this.doSubmitEntryOrder = true;
            }
        }

        private decimal CalculateStrike(decimal price, decimal basis = 5) {
            return basis * Math.Round(price/basis);
        }
    }
}

```
#### System Information
Ran in QuantConnect Cloud

#### Checklist

- [ X] I have completely filled out this template
- [ X] I have confirmed that this issue exists on the current `master` branch
- [ X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [ X] I have provided detailed steps to reproduce the issue

**Comment by heikohaensel** [comment]
Hello Martin,
thank your for the answer. You're right that the inversion of the price is not correct and the Combo would never get a fill.
I tried your adjusted code. Anyway it is working wrong, because it is not creating orders which would close the Iron Fly position at the Limit price, but it would open another Iron Fly position. Looking in the Orders tab in the backtest results, you can see that the placed orders are the same as for the entry instead of being reversed.

**Comment by Martin-Molinero** [comment]
Hey @heikohaensel! 
Thanks for the clarification, your right it's failing to process the second fill, we will solve this ASAP
```
2023-03-09T13:51:59.7976265Z ERROR:: SecurityPortfolioModel.ProcessFill():  System.DivideByZeroException: Attempted to divide by zero.
   at System.Decimal.DecCalc.VarDecDiv(DecCalc& d1, DecCalc& d2)
   at System.Decimal.op_Division(Decimal d1, Decimal d2)
   at QuantConnect.Securities.SecurityPortfolioModel.ProcessFill(SecurityPortfolioManager portfolio, Security security, OrderEvent fill) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/Common/Securities/SecurityPortfolioModel.cs:line 172
```
