### ISSUE TITLE
The folder [/usr/share/dotnet/host/fxr] does not exist

### ISSUE THREAD

**Issue by alphaDev23** [QuantConnect/Lean#7569]
When using the quantconnect/lean:15996 docker image, I receive,
```
Compiling '/LeanCLI/main.py'...
A fatal error occurred. The folder [/usr/share/dotnet/host/fxr] does not exist
```
when executing `lean backtest <PROJECT>'

**Comment by Martin-Molinero** [comment]
Hey @alphaDev23! I can't seem to reproduce the issue, we would need more information. Can you run the backtest using `--verbose` and sharing the output? Believe the project can just be the default algorithm

**Comment by alphaDev23** [comment]
Below is the output.  Note, it runs without issue on 15854.

```
Context information:
  Python version: 3.8.10 (default, May 26 2023, 14:05:08) . [GCC 9.4.0]
  OS: Linux-5.4.0-166-generic-x86_64-with-glibc2.29
  Lean CLI version: 1.0.172
json_module_handler.get_and_build_module(): non-interactive: essential_properties_value with module Local: {}
json_module_handler.get_and_build_module(): non-interactive: required_properties_value with module Local: {}
LeanConfigConfigurer.ensure_module_installed(): _save_properties for module Local: []
A custom engine image: "registry.ubuntu.local/lean:15996" is being used!
Running 'registry.ubuntu.local/lean:15996' with the following configuration:
{
    'environment': {},
    'stop_signal': 'SIGINT',
    'mounts': [
        {'Target': '/Lean/Launcher/bin/Debug/config.json', 'Source': '/tmp/lean-cli-j7nlcrc4/config.json', 'Type': 'bind', 'ReadOnly': True},
        {'Target': '/lean-cli-start.sh', 'Source': '/tmp/lean-cli-bj4jey8g/lean-cli-start.sh', 'Type': 'bind', 'ReadOnly': True}
    ],
    'volumes': {
        '/home/ubuntu/DevOps/lean-cli/models1/ff1': {'bind': '/LeanCLI', 'mode': 'rw'},
        '/home/ubuntu/DevOps/lean-cli/models1/data': {'bind': '/Lean/Data', 'mode': 'rw'},
        '/home/ubuntu/DevOps/lean-cli/models1/ff1/backtests/2023-11-14_08-55-07': {'bind': '/Results', 'mode': 'rw'},
        '/home/ubuntu/DevOps/lean-cli/models1/storage': {'bind': '/Storage', 'mode': 'rw'}
    },
    'ports': {},
    'name': 'lean_cli_d0eae47904df44b68dc26d2e04cf3a2b',
    'entrypoint': ['bash', '/lean-cli-start.sh'],
    'detach': True,
    'hostname': 'titan6',
    'tty': True,
    'stdin_open': True,
    'runtime': 'nvidia',
    'device_requests': [{'Driver': 'nvidia', 'Count': -1, 'DeviceIDs': [], 'Capabilities': [['gpu']], 'Options': {}}],
    'extra_hosts': {'host.docker.internal': '172.17.0.1'},
    'network': 'lean_cli'
}
+ '[' -d /LeanCLI ']'
+ python -m compileall /LeanCLI/research.ipynb /LeanCLI/Slippage.py /LeanCLI/main.py /LeanCLI/CustomIndicators.py
+ exec dotnet QuantConnect.Lean.Launcher.dll
A fatal error occurred, the folder [/usr/share/dotnet/host/fxr] does not contain any version-numbered child folders
Traceback (most recent call last):
  File "/home/ubuntu/DevOps/lean-cli/lib/python3.8/site-packages/lean/main.py", line 94, in main
    lean.main(standalone_mode=False)
  File "/home/ubuntu/DevOps/lean-cli/lib/python3.8/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/ubuntu/DevOps/lean-cli/lib/python3.8/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/ubuntu/DevOps/lean-cli/lib/python3.8/site-packages/lean/click.py", line 159, in invoke
    result = super().invoke(ctx)
  File "/home/ubuntu/DevOps/lean-cli/lib/python3.8/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/ubuntu/DevOps/lean-cli/lib/python3.8/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/ubuntu/DevOps/lean-cli/lib/python3.8/site-packages/lean/commands/backtest.py", line 410, in backtest
    lean_runner.run_lean(lean_config,
  File "/home/ubuntu/DevOps/lean-cli/lib/python3.8/site-packages/lean/components/docker/lean_runner.py", line 168, in run_lean
    raise RuntimeError(
RuntimeError: Something went wrong while running 'ff1' in the 'backtesting' environment, the output is stored in 'ff1/backtests/2023-11-14_08-55-07'
```

**Comment by Martin-Molinero** [comment]
Hey @alphaDev23! We can't reproduce the issue in linux/windows. It seems you are using a custom image, seems probable there's something off with it. You can retest unsetting the engine version, pulling the latest lean version (using --update) and retrying. See `lean config list/unset/set` ref https://github.com/QuantConnect/lean-cli#lean-config-list

**Comment by alphaDev23** [comment]
Executing `RUN apt-get -y update --fix-missing && apt-get upgrade -y` in my container build appears to have caused the issue.
