### ISSUE TITLE
FractalAdaptiveMovingAverage thorws exception

### ISSUE THREAD

**Issue by superichmann** [QuantConnect/Lean#7659]
```
ERROR:: Runtime Error: Value was either too large or too small for a Decimal. in FractalAdaptiveMovingAverage.cs:line 111
 System.Exception: Value was either too large or too small for a Decimal. in FractalAdaptiveMovingAverage.cs:line 111
 ---> QuantConnect.Exceptions.SystemExceptionInterpreter+SanitizedException: Value was either too large or too small for a Decimal.
   at System.Number.ThrowOverflowException(TypeCode type)
   at System.Decimal.DecCalc.VarDecFromR8(Double input, DecCalc& result)
   at QuantConnect.Indicators.FractalAdaptiveMovingAverage.ComputeNextValue(IBaseDataBar input) in Indicators\FractalAdaptiveMovingAverage.cs:line 111
   at QuantConnect.Indicators.IndicatorBase`1.ValidateAndComputeNextValue(T input) in Indicators\IndicatorBase.cs:line 340
   at QuantConnect.Indicators.IndicatorBase`1.Update(IBaseData input) in Indicators\IndicatorBase.cs:line 259
   at QuantConnect.Algorithm.QCAlgorithm.<>c__DisplayClass549_0`1.<RegisterIndicator>b__2(Object sender, IBaseData consolidated) in Algorithm\QCAlgorithm.Indicators.cs:line 2361
   at QuantConnect.Data.Consolidators.DataConsolidator`1.OnDataConsolidated(IBaseData consolidated)
   at QuantConnect.Data.Consolidators.IdentityDataConsolidator`1.Update(T data)
   at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, ISynchronizer synchronizer, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ILeanManager leanManager, CancellationToken token)
   --- End of inner exception stack trace ---
```

line numbering might be wrong

**Comment by Martin-Molinero** [comment]
Hey @superichmann! Thank you for the report
Could you please share how to reproduce the issue? Will help us solved it asap

**Comment by superichmann** [comment]
:( its on my local machine on many symbols I dont know which one did the error since it does not appear in the log file...
you think if I will build lean on Debug and run Launcher it will give exact line numbers?
