### ISSUE TITLE
Unable to add python package to trade algo second time

### ISSUE THREAD

**Issue by demo055** [QuantConnect/Lean#7959]
when i add python package to requirements.txt it will work for first time, but second time it will not load pymysql package. In previous version of lean this was working properly. But now it is not working. Can you please help?

20240422 13:06:19.993 ERROR:: Loader.TryCreatePythonAlgorithm():  System.Exception: AlgorithmPythonWrapper(): No module named 'pymysql'
  at <module>
    import pymysql
 in server.py: line 12
  at <module>
    from server import Server
   at Python.Runtime.PythonException.ThrowLastAsClrException()
   at Python.Runtime.NewReferenceExtensions.BorrowOrThrow(NewReference& reference)
   at Python.Runtime.PyModule.Import(String name)
   at Python.Runtime.Py.Import(String name)
   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper..ctor(String moduleName) at AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs:line 93 in main.py: line 7
 No module named 'pymysql'
   at QuantConnect.AlgorithmFactory.Python.Wrappers.AlgorithmPythonWrapper..ctor(String moduleName) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/AlgorithmFactory/Python/Wrappers/AlgorithmPythonWrapper.cs:line 179
   at QuantConnect.AlgorithmFactory.Loader.TryCreatePythonAlgorithm(String assemblyPath, IAlgorithm& algorithmInstance, String& errorMessage) in /LeanCloud/CI.Builder/bin/Debug/src/QuantConnect/Lean/AlgorithmFactory/Loader.cs:line 173

**Comment by Martin-Molinero** [comment]
Hey @demo055!
Believe this issue has already been fixed. Please pull the latest lean image, `docker pull quantconnect/lean` and update the lean cli to it's latest version 1.0.190 `pip install --upgrade lean`, that should be enough to fix it, if it doesn't please try deleting the `lean_cli_pip` docker volume

**Comment by demo055** [comment]
thank you. Deleting all docker volumes helped :)
