### ISSUE TITLE
Live oanda environment + warmup + indicator issue

### ISSUE THREAD

**Issue by Jay-Jay-D** [QuantConnect/Lean#799]
This is a slightly modified `BasicTemplateForexAlgorithm`.
```cs
using QuantConnect.Data;
using QuantConnect.Indicators;
using System.Linq;

namespace QuantConnect.Algorithm.CSharp
{
    public class BasicTemplateForexAlgorithm : QCAlgorithm
    {
        IIndicator<IndicatorDataPoint> _indicator;

        public override void Initialize()
        {
            SetStartDate(2013, 10, 07);  //Set Start Date
            SetEndDate(2013, 10, 11);    //Set End Date
            SetCash(100000);             //Set Strategy Cash
            var eurusd = AddForex("EURUSD", Resolution.Minute, market:"oanda");
            AddForex("GBPUSD", Resolution.Minute, market: "oanda");
            AddForex("EURGBP", Resolution.Minute, market: "oanda");
            History(5, Resolution.Daily);
            History(5, Resolution.Hour);
            History(5, Resolution.Minute);            
            var history = History(System.TimeSpan.FromSeconds(5), Resolution.Second);
            foreach (var data in history.OrderBy(x => x.Time))
            {
                foreach (var key in data.Keys)
                {
                    Log(key.Value + ": " + data.Time + " > " + data[key].Value);
                }
            }

            SetWarmUp(120);
            _indicator = SMA(eurusd.Symbol, 120);

        }
        public override void OnData(Slice data)
        {
            // Print to console to verify that data is coming in
            foreach (var key in data.Keys)
            {
                Log(key.Value + ": " + data[key].Time + " > " + data[key].Value);
            }
        }
    }
}
```
Note that the only changes respect to the original are the indicator and the `SetWarmup` method.

When I try to run this algorithm in the **live-oanda environment**, the engine throws this error:
```
2017-03-14T20:04:35.9482036Z ERROR:: AlgorithmManager.Run(): RuntimeError: Consolidators update: System.ArgumentNullException: Received type of TradeBar but expected QuoteBar
Parameter name: data
   at QuantConnect.Data.Consolidators.DataConsolidator`1.Update(IBaseData data) in C:\Users\jjd\Downloads\Lean-master\Common\Data\Consolidators\DataConsolidator.cs:line 46
   at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, IDataFeed feed, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ICommandQueueHandler commands, CancellationToken token) in C:\Users\jjd\Downloads\Lean-master\Engine\AlgorithmManager.cs:line 485
2017-03-14T20:04:35.9502036Z TRACE:: Engine.Run(): Exiting Algorithm Manager
2017-03-14T20:04:35.9752036Z ERROR:: Engine.HandleAlgorithmError(): Breaking out of parent try catch: System.ArgumentNullException: Received type of TradeBar but expected QuoteBar
Parameter name: data
   at QuantConnect.Data.Consolidators.DataConsolidator`1.Update(IBaseData data) in C:\Users\jjd\Downloads\Lean-master\Common\Data\Consolidators\DataConsolidator.cs:line 46
   at QuantConnect.Lean.Engine.AlgorithmManager.Run(AlgorithmNodePacket job, IAlgorithm algorithm, IDataFeed feed, ITransactionHandler transactions, IResultHandler results, IRealTimeHandler realtime, ICommandQueueHandler commands, CancellationToken token) in C:\Users\jjd\Downloads\Lean-master\Engine\AlgorithmManager.cs:line 485
```
If the environment is `backtest`, the indicator isn’t instantiated or the warmup isn’t set, then there is no error.

**Comment by Jay-Jay-D** [comment]
Awesome! I just tried and works flawlessly.
That's what I call fast!
