### ISSUE TITLE
Unable to find fallback package folder 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder'.

### ISSUE THREAD

**Issue by alexandre-lecoq** [QuantConnect/Lean#8224]
#### Expected Behavior
Solution should open gracefully in vscode.

#### Actual Behavior
After following instructions for Lean development container, i get the following errors :
```
[Error - 5:21:44 AM] [LanguageServerProjectSystem] Error while loading /Lean/DownloaderDataProvider/QuantConnect.DownloaderDataProvider.Launcher.csproj: The "ResolvePackageAssets" task failed unexpectedly.
NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder'.
   at NuGet.Packaging.FallbackPackagePathResolver..ctor(String userPackageFolder, IEnumerable`1 fallbackPackageFolders)
   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(IEnumerable`1 packageFolders)
   at Microsoft.NET.Build.Tasks.NuGetPackageResolver.CreateResolver(LockFile lockFile)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheWriter..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader.CreateReaderFromDisk(ResolvePackageAssets task, Byte[] settingsHash)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.CacheReader..ctor(ResolvePackageAssets task)
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ReadItemGroups()
   at Microsoft.NET.Build.Tasks.ResolvePackageAssets.ExecuteCore()
   at Microsoft.NET.Build.Tasks.TaskBase.Execute()
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute()
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)
```

#### Reproducing the Problem

I followed the documentation here : https://github.com/QuantConnect/Lean/tree/master/.vscode
More specifically, option 2 "Lean Development Container".
1. got vs code
2. got docker
3. ran docker pull quantconnect/research:latest
4. ran git clone https://github.com/QuantConnect/Lean
5. opened folder with vs code
6. clicked "Reopen in Container"

After some time, I get error messages. They lead to the output tab where errors are displayed.
`NuGet.Packaging.Core.PackagingException: Unable to find fallback package folder 'C:\Program Files\dotnet\sdk\NuGetFallbackFolder'.`

#### System Information
Windows 11
Docker
VS code

#### Checklist

- [X] I have completely filled out this template
- [X] I have confirmed that this issue exists on the current `master` branch
- [X] I have confirmed that this is not a duplicate issue by searching [issues](https://github.com/QuantConnect/Lean/issues)

- [X] I have provided detailed steps to reproduce the issue

**Comment by Martin-Molinero** [comment]
Hey @alexandre-lecoq! Sorry not sure what's wrong here, we don't give support for local direct installations because many things can go wrong from one host to the other. To get it going python3.11, dotnet 6 & setting the pythonnet env would be enough. Suggest looking at our github actions and dockerfiles for more details.
