### ISSUE TITLE
Parallel Runner Threading Issue

### ISSUE THREAD

**Issue by jaredbroad** [QuantConnect/Lean#831]
User reported issue:

```
2017-04-05T16:43:06.6406003Z ERROR:: ParallelRunnerController.ProcessHoldQueue():  System.ArgumentNullException: Value cannot be null.
  at System.Threading.SemaphoreSlim.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
  at System.Collections.Concurrent.BlockingCollection`1.TryTakeWithNoTimeValidation(T& item, Int32 millisecondsTimeout, CancellationToken cancellationToken, CancellationTokenSource combinedTokenSource)
  at System.Collections.Concurrent.BlockingCollection`1.<GetConsumingEnumerable>d__68.MoveNext()
  at QuantConnect.Util.ParallelRunnerController.ProcessHoldQueue(CancellationToken token) in Lean\Common\Util\ParallelRunner.cs:line 120
```
Error shown after the performance summary approximately 1/10 times,

Backtesting on Windows 7 on a Intel Core i7-6700 CPU @ 3.40 GHz. 30 tickers with 30 minute bars.

**Comment by jaredbroad** [comment]
Fixed in PR #903
