### ISSUE TITLE
ToolBox OandaDownloader RestApiV1 Unable to cast TradeBar to QuoteBar - InvalidCastException

### ISSUE THREAD

**Issue by tomhunter-gh** [QuantConnect/Lean#895]
Hi Jared, I downloaded the v2.4.0.0 release and tried to run the Oanda data downloader (I switched the ToolBox project startup object to `QuantConnect.ToolBox.OandaDownloader.Program`), but unfortunately I'm getting the following error:

> ERROR:: Program.Main():  System.InvalidCastException: Unable to cast object of type 'QuantConnect.Data.Market.TradeBar' to type 'QuantConnect.Data.Market.QuoteBar'.

The complete output is as follows (I blanked out my account id but I'm using an API v1 type account id):

	C:\Users\tomhu\Downloads\Lean-2.4.0.0\ToolBox\bin\Debug>QuantConnect.ToolBox.exe EURUSD Daily 20150101 20150102
	20170506 19:45:34 Trace:: Config.Get(): Configuration key not found. Key: data-directory - Using default value: ../../../Data
	20170506 19:45:34 Trace:: Config.Get(): Configuration key not found. Key: access-token - Using default value: ·································································
	20170506 19:45:34 Trace:: Config.Get(): Configuration key not found. Key: account-id - Using default value: ·······
	20170506 19:45:34 Trace:: Config.Get(): Configuration key not found. Key: map-file-provider - Using default value: LocalDiskMapFileProvider
	20170506 19:46:02 ERROR:: Program.Main():  System.InvalidCastException: Unable to cast object of type 'QuantConnect.Data.Market.TradeBar' to type 'QuantConnect.Data.Market.QuoteBar'.
	   at QuantConnect.Util.LeanData.GenerateLine(IBaseData data, SecurityType securityType, Resolution resolution) in C:\Users\tomhu\Downloads\Lean-2.4.0.0\Common\Util\LeanData.cs:line 94
	   at QuantConnect.ToolBox.LeanDataWriter.<WriteDailyOrHour>b__9_1(BaseData x) in C:\Users\tomhu\Downloads\Lean-2.4.0.0\ToolBox\LeanDataWriter.cs:line 145
	   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
	   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
	   at QuantConnect.ToolBox.LeanDataWriter.WriteDailyOrHour(IEnumerable`1 source) in C:\Users\tomhu\Downloads\Lean-2.4.0.0\ToolBox\LeanDataWriter.cs:line 145
	   at QuantConnect.ToolBox.LeanDataWriter.Write(IEnumerable`1 source) in C:\Users\tomhu\Downloads\Lean-2.4.0.0\ToolBox\LeanDataWriter.cs:line 80
	   at QuantConnect.ToolBox.OandaDownloader.Program.Main(String[] args) in C:\Users\tomhu\Downloads\Lean-2.4.0.0\ToolBox\OandaDownloader\Program.cs:line 96

Please let me know if this is the current mechanism to download Oanda data.  If so, please could you confirm that the correct approach is to manually switch the project startup object and also either hard code  or add a config.json with the Oanda access token and account id?

Thanks,
Tom

**Comment by tomhunter-gh** [comment]
The usage text suggests you run a program called `OandaDownloader`:

![image](https://cloud.githubusercontent.com/assets/1420946/25775177/82ef6412-3297-11e7-9bc7-ab5358f4e78a.png)

But the csproj produces `QuantConnect.ToolBox.exe` - please let me know if I'm missing anything or if the usage text is just out of date.  Thanks

**Comment by jaredbroad** [comment]
Addressed in PR https://github.com/QuantConnect/Lean/pull/897
