### ISSUE TITLE
Security.ExecuteWithTimeLimit(): Algorithm took longer than 10 minutes on a single time loop.

### ISSUE THREAD

**Issue by mayurbakhai** [QuantConnect/Lean#977]
Hi QC Team,

Sorry to reopen #144 . I came across this error for second time in a week on IB paper account. Trace from log file is below. Note that I am recording data from my algo and writing transactions to a local file from within `OnOrderEvent()`, all of this within my algo. I pulled LEAN from github about 2 weeks ago and haven't updated changes since. I made one change to the code - inside InteractiveBrokersBrokerage.cs as described in #971 wrt order expiry. Can you please take a look?

```
2017-06-14T16:17:05.2033920Z TRACE:: 2017-06-14 11:17:05Z Isolator.ExecuteWithTimeLimit(): Used: 14 Sample: 16
2017-06-14T16:18:05.2559756Z TRACE:: 2017-06-14 11:18:05Z Isolator.ExecuteWithTimeLimit(): Used: 15 Sample: 14
2017-06-14T16:19:05.2825562Z TRACE:: 2017-06-14 11:19:05Z Isolator.ExecuteWithTimeLimit(): Used: 14 Sample: 15
2017-06-14T16:20:05.3155153Z TRACE:: 2017-06-14 11:20:05Z Isolator.ExecuteWithTimeLimit(): Used: 15 Sample: 9
2017-06-14T16:21:05.3548919Z TRACE:: 2017-06-14 11:21:05Z Isolator.ExecuteWithTimeLimit(): Used: 15 Sample: 17
2017-06-14T16:34:22.7620037Z TRACE:: 2017-06-14 11:22:05Z Isolator.ExecuteWithTimeLimit(): Used: 14 Sample: 12
2017-06-14T16:34:22.7639625Z TRACE:: BrokerageTransactionHandler.Process(): 6/14/2017 16:24:00 UTC: Submit Order: (14) - OrderId: 14 New Limit order for -200 units of SPY at limit 244.19  Status: Unprocessed
2017-06-14T16:34:22.7920008Z TRACE:: InteractiveBrokersBrokerage.PlaceOrder(): Symbol: SPY Quantity: -200
2017-06-14T16:34:22.7930018Z TRACE:: Order created at: 20170614 11:24:00 and order expires at: 20170614 11:24:02
2017-06-14T16:34:22.8079939Z ERROR:: AlgorithmManager.Run(): CancellationRequestion at 6/14/2017 16:24:01
2017-06-14T16:34:22.8079939Z ERROR:: Security.ExecuteWithTimeLimit(): Algorithm took longer than 10 minutes on a single time loop.
2017-06-14T16:34:22.8089946Z TRACE:: Engine.Run(): Exiting Algorithm Manager
2017-06-14T16:34:22.8240250Z TRACE:: InteractiveBrokersBrokerage.HandleOrderStatusUpdates(): OrderId: 500, Status: Inactive, Filled: 0, Remaining: 200, AverageFillPrice: 0, PermId: 1701919355, ParentId: 0, LastFillPrice: 0, ClientId: 1, WhyHeld: 
2017-06-14T16:34:22.8270069Z ERROR:: InteractiveBrokersBrokerage.ConvertOrderStatus(): Inactive order
2017-06-14T16:34:22.8270069Z TRACE:: BrokerageTransactionHandler.OrderStatusChanged(): Time: 6/14/2017 16:34:22 OrderID: 14 Symbol: SPY Status: None Message: Interactive Brokers Order Event BrokerId: 500
2017-06-14T16:34:22.8510237Z ERROR:: Engine.HandleAlgorithmError(): Breaking out of parent try catch: System.Exception: Algorithm took longer than 10 minutes on a single time loop.
   at QuantConnect.Isolator.ExecuteWithTimeLimit(TimeSpan timeSpan, Func`1 withinCustomLimits, Action codeBlock, Int64 memoryCap) in C:\Users\mayur\Documents\Projects\Lean\Common\Isolator.cs:line 136
   at QuantConnect.Lean.Engine.Engine.Run(AlgorithmNodePacket job, String assemblyPath) in C:\Users\mayur\Documents\Projects\Lean\Engine\Engine.cs:line 249
```

**Comment by michaelsrew** [comment]
Hi 
1) i had a similar problem once but it was a problem with foreign currence balance in my account (eur) where the subsrcription failed to eur.usd and it crashed.  But your account is USD only?
2) So there is "CancellationRequestion at 6/14/2017 16:24:01" but what happend at 16:14? or later? there is only info starting at 11:17 in your log......... what happend at 11:14? or 11:13?
best regards

**Comment by mayurbakhai** [comment]
Hi Michael,

1. Yes account is USD only
2. Log looks similar before 11:17 to what it is at 11:17 through 11:22. What I am trying to understand is the log timestamp jumps from 16:21 to 16:34 where it would have got stuck, there's no trace/debug statement.

Would appreciate any help on this!

**Comment by michaelsrew** [comment]
hmmm and that's not a virtual machine with crazy drifting time? where time sync over 10 minutes could have killed the algo....

**Comment by jaredbroad** [comment]
We recently fixed an issue where subscribing to too many feeds threw and exception in the data thread and it hung the primary algorithm thread - causing these errors. Can you update to master and report back if you see the issue again? If you see the issue again can you share the algorithm, number of datafeeds, details on its implementation.. etc.
https://github.com/QuantConnect/Lean/pull/985

**Comment by mayurbakhai** [comment]
Thank you for the fix! I think I am using only IB's datafeed. I'll run it for couple of days and will report back if I see it come up again.

**Comment by jaredbroad** [comment]
IB by default only supports 100 symbols; you'll have to contact them for an upgrade pack to get more.
